/*
ConfigCat Public Management API

Testing SegmentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package configcatpublicapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/configcat/configcat-publicapi-go-client/v3"
)

func Test_configcatpublicapi_SegmentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SegmentsAPIService CreateSegment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.SegmentsAPI.CreateSegment(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SegmentsAPIService DeleteSegment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var segmentId string

		httpRes, err := apiClient.SegmentsAPI.DeleteSegment(context.Background(), segmentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SegmentsAPIService GetSegment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var segmentId string

		resp, httpRes, err := apiClient.SegmentsAPI.GetSegment(context.Background(), segmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SegmentsAPIService GetSegments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.SegmentsAPI.GetSegments(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SegmentsAPIService UpdateSegment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var segmentId string

		resp, httpRes, err := apiClient.SegmentsAPI.UpdateSegment(context.Background(), segmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
