/*
ConfigCat Public Management API

Testing TagsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package configcat-publicapi-go-client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_configcat-publicapi-go-client_TagsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TagsApiService CreateTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.TagsApi.CreateTag(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TagsApiService DeleteTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tagId int64

		httpRes, err := apiClient.TagsApi.DeleteTag(context.Background(), tagId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TagsApiService GetSettingsByTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tagId int64

		resp, httpRes, err := apiClient.TagsApi.GetSettingsByTag(context.Background(), tagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TagsApiService GetTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tagId int64

		resp, httpRes, err := apiClient.TagsApi.GetTag(context.Background(), tagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TagsApiService GetTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.TagsApi.GetTags(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TagsApiService UpdateTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tagId int64

		resp, httpRes, err := apiClient.TagsApi.UpdateTag(context.Background(), tagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
