/*
ConfigCat Public Management API

Testing CodeReferencesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package configcatpublicapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/configcat/configcat-publicapi-go-client/v3"
)

func Test_configcatpublicapi_CodeReferencesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CodeReferencesAPIService V1CodeReferencesDeleteReportsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CodeReferencesAPI.V1CodeReferencesDeleteReportsPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CodeReferencesAPIService V1CodeReferencesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CodeReferencesAPI.V1CodeReferencesPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CodeReferencesAPIService V1SettingsSettingIdCodeReferencesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var settingId int32

		resp, httpRes, err := apiClient.CodeReferencesAPI.V1SettingsSettingIdCodeReferencesGet(context.Background(), settingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
