/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PagingResponseInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagingResponseInfo{}

// PagingResponseInfo struct for PagingResponseInfo
type PagingResponseInfo struct {
	CurrentPage int32 `json:"currentPage"`
	TotalPages int32 `json:"totalPages"`
	PageSize int32 `json:"pageSize"`
	TotalCount int32 `json:"totalCount"`
	HasPrevious bool `json:"hasPrevious"`
	HasNext bool `json:"hasNext"`
	AdditionalProperties map[string]interface{}
}

type _PagingResponseInfo PagingResponseInfo

// NewPagingResponseInfo instantiates a new PagingResponseInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagingResponseInfo(currentPage int32, totalPages int32, pageSize int32, totalCount int32, hasPrevious bool, hasNext bool) *PagingResponseInfo {
	this := PagingResponseInfo{}
	this.CurrentPage = currentPage
	this.TotalPages = totalPages
	this.PageSize = pageSize
	this.TotalCount = totalCount
	this.HasPrevious = hasPrevious
	this.HasNext = hasNext
	return &this
}

// NewPagingResponseInfoWithDefaults instantiates a new PagingResponseInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagingResponseInfoWithDefaults() *PagingResponseInfo {
	this := PagingResponseInfo{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value
func (o *PagingResponseInfo) GetCurrentPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value
// and a boolean to check if the value has been set.
func (o *PagingResponseInfo) GetCurrentPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPage, true
}

// SetCurrentPage sets field value
func (o *PagingResponseInfo) SetCurrentPage(v int32) {
	o.CurrentPage = v
}

// GetTotalPages returns the TotalPages field value
func (o *PagingResponseInfo) GetTotalPages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *PagingResponseInfo) GetTotalPagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *PagingResponseInfo) SetTotalPages(v int32) {
	o.TotalPages = v
}

// GetPageSize returns the PageSize field value
func (o *PagingResponseInfo) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *PagingResponseInfo) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *PagingResponseInfo) SetPageSize(v int32) {
	o.PageSize = v
}

// GetTotalCount returns the TotalCount field value
func (o *PagingResponseInfo) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *PagingResponseInfo) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *PagingResponseInfo) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetHasPrevious returns the HasPrevious field value
func (o *PagingResponseInfo) GetHasPrevious() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasPrevious
}

// GetHasPreviousOk returns a tuple with the HasPrevious field value
// and a boolean to check if the value has been set.
func (o *PagingResponseInfo) GetHasPreviousOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasPrevious, true
}

// SetHasPrevious sets field value
func (o *PagingResponseInfo) SetHasPrevious(v bool) {
	o.HasPrevious = v
}

// GetHasNext returns the HasNext field value
func (o *PagingResponseInfo) GetHasNext() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value
// and a boolean to check if the value has been set.
func (o *PagingResponseInfo) GetHasNextOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasNext, true
}

// SetHasNext sets field value
func (o *PagingResponseInfo) SetHasNext(v bool) {
	o.HasNext = v
}

func (o PagingResponseInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagingResponseInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currentPage"] = o.CurrentPage
	toSerialize["totalPages"] = o.TotalPages
	toSerialize["pageSize"] = o.PageSize
	toSerialize["totalCount"] = o.TotalCount
	toSerialize["hasPrevious"] = o.HasPrevious
	toSerialize["hasNext"] = o.HasNext

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PagingResponseInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currentPage",
		"totalPages",
		"pageSize",
		"totalCount",
		"hasPrevious",
		"hasNext",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPagingResponseInfo := _PagingResponseInfo{}

	err = json.Unmarshal(data, &varPagingResponseInfo)

	if err != nil {
		return err
	}

	*o = PagingResponseInfo(varPagingResponseInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "currentPage")
		delete(additionalProperties, "totalPages")
		delete(additionalProperties, "pageSize")
		delete(additionalProperties, "totalCount")
		delete(additionalProperties, "hasPrevious")
		delete(additionalProperties, "hasNext")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePagingResponseInfo struct {
	value *PagingResponseInfo
	isSet bool
}

func (v NullablePagingResponseInfo) Get() *PagingResponseInfo {
	return v.value
}

func (v *NullablePagingResponseInfo) Set(val *PagingResponseInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePagingResponseInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePagingResponseInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagingResponseInfo(val *PagingResponseInfo) *NullablePagingResponseInfo {
	return &NullablePagingResponseInfo{value: val, isSet: true}
}

func (v NullablePagingResponseInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagingResponseInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


