/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
)

// checks if the UpdateConditionModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateConditionModel{}

// UpdateConditionModel struct for UpdateConditionModel
type UpdateConditionModel struct {
	UserCondition NullableUpdateUserConditionModel `json:"userCondition,omitempty"`
	SegmentCondition NullableUpdateSegmentConditionModel `json:"segmentCondition,omitempty"`
	PrerequisiteFlagCondition NullableUpdatePrerequisiteFlagConditionModel `json:"prerequisiteFlagCondition,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateConditionModel UpdateConditionModel

// NewUpdateConditionModel instantiates a new UpdateConditionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateConditionModel() *UpdateConditionModel {
	this := UpdateConditionModel{}
	return &this
}

// NewUpdateConditionModelWithDefaults instantiates a new UpdateConditionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateConditionModelWithDefaults() *UpdateConditionModel {
	this := UpdateConditionModel{}
	return &this
}

// GetUserCondition returns the UserCondition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConditionModel) GetUserCondition() UpdateUserConditionModel {
	if o == nil || IsNil(o.UserCondition.Get()) {
		var ret UpdateUserConditionModel
		return ret
	}
	return *o.UserCondition.Get()
}

// GetUserConditionOk returns a tuple with the UserCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConditionModel) GetUserConditionOk() (*UpdateUserConditionModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserCondition.Get(), o.UserCondition.IsSet()
}

// HasUserCondition returns a boolean if a field has been set.
func (o *UpdateConditionModel) HasUserCondition() bool {
	if o != nil && o.UserCondition.IsSet() {
		return true
	}

	return false
}

// SetUserCondition gets a reference to the given NullableUpdateUserConditionModel and assigns it to the UserCondition field.
func (o *UpdateConditionModel) SetUserCondition(v UpdateUserConditionModel) {
	o.UserCondition.Set(&v)
}
// SetUserConditionNil sets the value for UserCondition to be an explicit nil
func (o *UpdateConditionModel) SetUserConditionNil() {
	o.UserCondition.Set(nil)
}

// UnsetUserCondition ensures that no value is present for UserCondition, not even an explicit nil
func (o *UpdateConditionModel) UnsetUserCondition() {
	o.UserCondition.Unset()
}

// GetSegmentCondition returns the SegmentCondition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConditionModel) GetSegmentCondition() UpdateSegmentConditionModel {
	if o == nil || IsNil(o.SegmentCondition.Get()) {
		var ret UpdateSegmentConditionModel
		return ret
	}
	return *o.SegmentCondition.Get()
}

// GetSegmentConditionOk returns a tuple with the SegmentCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConditionModel) GetSegmentConditionOk() (*UpdateSegmentConditionModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.SegmentCondition.Get(), o.SegmentCondition.IsSet()
}

// HasSegmentCondition returns a boolean if a field has been set.
func (o *UpdateConditionModel) HasSegmentCondition() bool {
	if o != nil && o.SegmentCondition.IsSet() {
		return true
	}

	return false
}

// SetSegmentCondition gets a reference to the given NullableUpdateSegmentConditionModel and assigns it to the SegmentCondition field.
func (o *UpdateConditionModel) SetSegmentCondition(v UpdateSegmentConditionModel) {
	o.SegmentCondition.Set(&v)
}
// SetSegmentConditionNil sets the value for SegmentCondition to be an explicit nil
func (o *UpdateConditionModel) SetSegmentConditionNil() {
	o.SegmentCondition.Set(nil)
}

// UnsetSegmentCondition ensures that no value is present for SegmentCondition, not even an explicit nil
func (o *UpdateConditionModel) UnsetSegmentCondition() {
	o.SegmentCondition.Unset()
}

// GetPrerequisiteFlagCondition returns the PrerequisiteFlagCondition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConditionModel) GetPrerequisiteFlagCondition() UpdatePrerequisiteFlagConditionModel {
	if o == nil || IsNil(o.PrerequisiteFlagCondition.Get()) {
		var ret UpdatePrerequisiteFlagConditionModel
		return ret
	}
	return *o.PrerequisiteFlagCondition.Get()
}

// GetPrerequisiteFlagConditionOk returns a tuple with the PrerequisiteFlagCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConditionModel) GetPrerequisiteFlagConditionOk() (*UpdatePrerequisiteFlagConditionModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrerequisiteFlagCondition.Get(), o.PrerequisiteFlagCondition.IsSet()
}

// HasPrerequisiteFlagCondition returns a boolean if a field has been set.
func (o *UpdateConditionModel) HasPrerequisiteFlagCondition() bool {
	if o != nil && o.PrerequisiteFlagCondition.IsSet() {
		return true
	}

	return false
}

// SetPrerequisiteFlagCondition gets a reference to the given NullableUpdatePrerequisiteFlagConditionModel and assigns it to the PrerequisiteFlagCondition field.
func (o *UpdateConditionModel) SetPrerequisiteFlagCondition(v UpdatePrerequisiteFlagConditionModel) {
	o.PrerequisiteFlagCondition.Set(&v)
}
// SetPrerequisiteFlagConditionNil sets the value for PrerequisiteFlagCondition to be an explicit nil
func (o *UpdateConditionModel) SetPrerequisiteFlagConditionNil() {
	o.PrerequisiteFlagCondition.Set(nil)
}

// UnsetPrerequisiteFlagCondition ensures that no value is present for PrerequisiteFlagCondition, not even an explicit nil
func (o *UpdateConditionModel) UnsetPrerequisiteFlagCondition() {
	o.PrerequisiteFlagCondition.Unset()
}

func (o UpdateConditionModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateConditionModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.UserCondition.IsSet() {
		toSerialize["userCondition"] = o.UserCondition.Get()
	}
	if o.SegmentCondition.IsSet() {
		toSerialize["segmentCondition"] = o.SegmentCondition.Get()
	}
	if o.PrerequisiteFlagCondition.IsSet() {
		toSerialize["prerequisiteFlagCondition"] = o.PrerequisiteFlagCondition.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateConditionModel) UnmarshalJSON(data []byte) (err error) {
	varUpdateConditionModel := _UpdateConditionModel{}

	err = json.Unmarshal(data, &varUpdateConditionModel)

	if err != nil {
		return err
	}

	*o = UpdateConditionModel(varUpdateConditionModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "userCondition")
		delete(additionalProperties, "segmentCondition")
		delete(additionalProperties, "prerequisiteFlagCondition")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateConditionModel struct {
	value *UpdateConditionModel
	isSet bool
}

func (v NullableUpdateConditionModel) Get() *UpdateConditionModel {
	return v.value
}

func (v *NullableUpdateConditionModel) Set(val *UpdateConditionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateConditionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateConditionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateConditionModel(val *UpdateConditionModel) *NullableUpdateConditionModel {
	return &NullableUpdateConditionModel{value: val, isSet: true}
}

func (v NullableUpdateConditionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateConditionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


