/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PredefinedVariationValueModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PredefinedVariationValueModel{}

// PredefinedVariationValueModel Represents the value of a Predefined Variation.
type PredefinedVariationValueModel struct {
	// The served value in case of a boolean Feature Flag.
	BoolValue NullableBool `json:"boolValue"`
	// The served value in case of a text Setting.
	StringValue NullableString `json:"stringValue"`
	// The served value in case of a whole number Setting.
	IntValue NullableInt32 `json:"intValue"`
	// The served value in case of a decimal number Setting.
	DoubleValue NullableFloat64 `json:"doubleValue"`
	AdditionalProperties map[string]interface{}
}

type _PredefinedVariationValueModel PredefinedVariationValueModel

// NewPredefinedVariationValueModel instantiates a new PredefinedVariationValueModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPredefinedVariationValueModel(boolValue NullableBool, stringValue NullableString, intValue NullableInt32, doubleValue NullableFloat64) *PredefinedVariationValueModel {
	this := PredefinedVariationValueModel{}
	this.BoolValue = boolValue
	this.StringValue = stringValue
	this.IntValue = intValue
	this.DoubleValue = doubleValue
	return &this
}

// NewPredefinedVariationValueModelWithDefaults instantiates a new PredefinedVariationValueModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPredefinedVariationValueModelWithDefaults() *PredefinedVariationValueModel {
	this := PredefinedVariationValueModel{}
	return &this
}

// GetBoolValue returns the BoolValue field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *PredefinedVariationValueModel) GetBoolValue() bool {
	if o == nil || o.BoolValue.Get() == nil {
		var ret bool
		return ret
	}

	return *o.BoolValue.Get()
}

// GetBoolValueOk returns a tuple with the BoolValue field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PredefinedVariationValueModel) GetBoolValueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.BoolValue.Get(), o.BoolValue.IsSet()
}

// SetBoolValue sets field value
func (o *PredefinedVariationValueModel) SetBoolValue(v bool) {
	o.BoolValue.Set(&v)
}

// GetStringValue returns the StringValue field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PredefinedVariationValueModel) GetStringValue() string {
	if o == nil || o.StringValue.Get() == nil {
		var ret string
		return ret
	}

	return *o.StringValue.Get()
}

// GetStringValueOk returns a tuple with the StringValue field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PredefinedVariationValueModel) GetStringValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StringValue.Get(), o.StringValue.IsSet()
}

// SetStringValue sets field value
func (o *PredefinedVariationValueModel) SetStringValue(v string) {
	o.StringValue.Set(&v)
}

// GetIntValue returns the IntValue field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PredefinedVariationValueModel) GetIntValue() int32 {
	if o == nil || o.IntValue.Get() == nil {
		var ret int32
		return ret
	}

	return *o.IntValue.Get()
}

// GetIntValueOk returns a tuple with the IntValue field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PredefinedVariationValueModel) GetIntValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntValue.Get(), o.IntValue.IsSet()
}

// SetIntValue sets field value
func (o *PredefinedVariationValueModel) SetIntValue(v int32) {
	o.IntValue.Set(&v)
}

// GetDoubleValue returns the DoubleValue field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *PredefinedVariationValueModel) GetDoubleValue() float64 {
	if o == nil || o.DoubleValue.Get() == nil {
		var ret float64
		return ret
	}

	return *o.DoubleValue.Get()
}

// GetDoubleValueOk returns a tuple with the DoubleValue field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PredefinedVariationValueModel) GetDoubleValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.DoubleValue.Get(), o.DoubleValue.IsSet()
}

// SetDoubleValue sets field value
func (o *PredefinedVariationValueModel) SetDoubleValue(v float64) {
	o.DoubleValue.Set(&v)
}

func (o PredefinedVariationValueModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PredefinedVariationValueModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["boolValue"] = o.BoolValue.Get()
	toSerialize["stringValue"] = o.StringValue.Get()
	toSerialize["intValue"] = o.IntValue.Get()
	toSerialize["doubleValue"] = o.DoubleValue.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PredefinedVariationValueModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"boolValue",
		"stringValue",
		"intValue",
		"doubleValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPredefinedVariationValueModel := _PredefinedVariationValueModel{}

	err = json.Unmarshal(data, &varPredefinedVariationValueModel)

	if err != nil {
		return err
	}

	*o = PredefinedVariationValueModel(varPredefinedVariationValueModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "boolValue")
		delete(additionalProperties, "stringValue")
		delete(additionalProperties, "intValue")
		delete(additionalProperties, "doubleValue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePredefinedVariationValueModel struct {
	value *PredefinedVariationValueModel
	isSet bool
}

func (v NullablePredefinedVariationValueModel) Get() *PredefinedVariationValueModel {
	return v.value
}

func (v *NullablePredefinedVariationValueModel) Set(val *PredefinedVariationValueModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePredefinedVariationValueModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePredefinedVariationValueModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePredefinedVariationValueModel(val *PredefinedVariationValueModel) *NullablePredefinedVariationValueModel {
	return &NullablePredefinedVariationValueModel{value: val, isSet: true}
}

func (v NullablePredefinedVariationValueModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePredefinedVariationValueModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


