/*
ConfigCat Public Management API

**Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The purpose of this API is to access the ConfigCat platform programmatically.  You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.   The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  and JSON+HAL format. Do not use this API for accessing and evaluating feature flag values. Use the [SDKs instead](https://configcat.com/docs/sdk-reference/overview).   # OpenAPI Specification  The complete specification is publicly available here: [swagger.json](v1/swagger.json).  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
)

// checks if the ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks{}

// ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks struct for ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks
type ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks struct {
	Products *string `json:"products,omitempty"`
	Members *string `json:"members,omitempty"`
}

// NewConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks instantiates a new ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks() *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks {
	this := ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks{}
	return &this
}

// NewConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinksWithDefaults instantiates a new ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinksWithDefaults() *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks {
	this := ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks{}
	return &this
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) GetProducts() string {
	if o == nil || IsNil(o.Products) {
		var ret string
		return ret
	}
	return *o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) GetProductsOk() (*string, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given string and assigns it to the Products field.
func (o *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) SetProducts(v string) {
	o.Products = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) GetMembers() string {
	if o == nil || IsNil(o.Members) {
		var ret string
		return ret
	}
	return *o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) GetMembersOk() (*string, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given string and assigns it to the Members field.
func (o *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) SetMembers(v string) {
	o.Members = &v
}

func (o ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	return toSerialize, nil
}

type NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks struct {
	value *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks
	isSet bool
}

func (v NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) Get() *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks {
	return v.value
}

func (v *NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) Set(val *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks(val *ConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) *NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks {
	return &NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks{value: val, isSet: true}
}

func (v NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigModelHaljsonEmbeddedProductEmbeddedOrganizationLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


