/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ConfigSettingValueModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigSettingValueModel{}

// ConfigSettingValueModel struct for ConfigSettingValueModel
type ConfigSettingValueModel struct {
	Setting SettingDataModel `json:"setting"`
	// The last updated date and time when the Feature Flag or Setting.
	UpdatedAt NullableTime `json:"updatedAt"`
	// The email of the user who last updated the Feature Flag or Setting.
	LastUpdaterUserEmail NullableString `json:"lastUpdaterUserEmail"`
	// The name of the user who last updated the Feature Flag or Setting.
	LastUpdaterUserFullName NullableString `json:"lastUpdaterUserFullName"`
	// The integration links attached to the Feature Flag or Setting.
	IntegrationLinks []IntegrationLinkModel `json:"integrationLinks"`
	// The tags attached to the Feature Flag or Setting.
	SettingTags []SettingTagModel `json:"settingTags"`
	// The targeting rule collection.
	RolloutRules []RolloutRuleModel `json:"rolloutRules"`
	// The percentage rule collection.
	RolloutPercentageItems []RolloutPercentageItemModel `json:"rolloutPercentageItems"`
	// The value to serve. It must respect the setting type. In some generated clients for strictly typed languages you may use double/float properties to handle integer values.
	Value SettingValueType `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _ConfigSettingValueModel ConfigSettingValueModel

// NewConfigSettingValueModel instantiates a new ConfigSettingValueModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigSettingValueModel(setting SettingDataModel, updatedAt NullableTime, lastUpdaterUserEmail NullableString, lastUpdaterUserFullName NullableString, integrationLinks []IntegrationLinkModel, settingTags []SettingTagModel, rolloutRules []RolloutRuleModel, rolloutPercentageItems []RolloutPercentageItemModel, value SettingValueType) *ConfigSettingValueModel {
	this := ConfigSettingValueModel{}
	this.Setting = setting
	this.UpdatedAt = updatedAt
	this.LastUpdaterUserEmail = lastUpdaterUserEmail
	this.LastUpdaterUserFullName = lastUpdaterUserFullName
	this.IntegrationLinks = integrationLinks
	this.SettingTags = settingTags
	this.RolloutRules = rolloutRules
	this.RolloutPercentageItems = rolloutPercentageItems
	this.Value = value
	return &this
}

// NewConfigSettingValueModelWithDefaults instantiates a new ConfigSettingValueModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigSettingValueModelWithDefaults() *ConfigSettingValueModel {
	this := ConfigSettingValueModel{}
	return &this
}

// GetSetting returns the Setting field value
func (o *ConfigSettingValueModel) GetSetting() SettingDataModel {
	if o == nil {
		var ret SettingDataModel
		return ret
	}

	return o.Setting
}

// GetSettingOk returns a tuple with the Setting field value
// and a boolean to check if the value has been set.
func (o *ConfigSettingValueModel) GetSettingOk() (*SettingDataModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Setting, true
}

// SetSetting sets field value
func (o *ConfigSettingValueModel) SetSetting(v SettingDataModel) {
	o.Setting = v
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ConfigSettingValueModel) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigSettingValueModel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *ConfigSettingValueModel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// GetLastUpdaterUserEmail returns the LastUpdaterUserEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ConfigSettingValueModel) GetLastUpdaterUserEmail() string {
	if o == nil || o.LastUpdaterUserEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdaterUserEmail.Get()
}

// GetLastUpdaterUserEmailOk returns a tuple with the LastUpdaterUserEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigSettingValueModel) GetLastUpdaterUserEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdaterUserEmail.Get(), o.LastUpdaterUserEmail.IsSet()
}

// SetLastUpdaterUserEmail sets field value
func (o *ConfigSettingValueModel) SetLastUpdaterUserEmail(v string) {
	o.LastUpdaterUserEmail.Set(&v)
}

// GetLastUpdaterUserFullName returns the LastUpdaterUserFullName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ConfigSettingValueModel) GetLastUpdaterUserFullName() string {
	if o == nil || o.LastUpdaterUserFullName.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdaterUserFullName.Get()
}

// GetLastUpdaterUserFullNameOk returns a tuple with the LastUpdaterUserFullName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigSettingValueModel) GetLastUpdaterUserFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdaterUserFullName.Get(), o.LastUpdaterUserFullName.IsSet()
}

// SetLastUpdaterUserFullName sets field value
func (o *ConfigSettingValueModel) SetLastUpdaterUserFullName(v string) {
	o.LastUpdaterUserFullName.Set(&v)
}

// GetIntegrationLinks returns the IntegrationLinks field value
func (o *ConfigSettingValueModel) GetIntegrationLinks() []IntegrationLinkModel {
	if o == nil {
		var ret []IntegrationLinkModel
		return ret
	}

	return o.IntegrationLinks
}

// GetIntegrationLinksOk returns a tuple with the IntegrationLinks field value
// and a boolean to check if the value has been set.
func (o *ConfigSettingValueModel) GetIntegrationLinksOk() ([]IntegrationLinkModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntegrationLinks, true
}

// SetIntegrationLinks sets field value
func (o *ConfigSettingValueModel) SetIntegrationLinks(v []IntegrationLinkModel) {
	o.IntegrationLinks = v
}

// GetSettingTags returns the SettingTags field value
func (o *ConfigSettingValueModel) GetSettingTags() []SettingTagModel {
	if o == nil {
		var ret []SettingTagModel
		return ret
	}

	return o.SettingTags
}

// GetSettingTagsOk returns a tuple with the SettingTags field value
// and a boolean to check if the value has been set.
func (o *ConfigSettingValueModel) GetSettingTagsOk() ([]SettingTagModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.SettingTags, true
}

// SetSettingTags sets field value
func (o *ConfigSettingValueModel) SetSettingTags(v []SettingTagModel) {
	o.SettingTags = v
}

// GetRolloutRules returns the RolloutRules field value
func (o *ConfigSettingValueModel) GetRolloutRules() []RolloutRuleModel {
	if o == nil {
		var ret []RolloutRuleModel
		return ret
	}

	return o.RolloutRules
}

// GetRolloutRulesOk returns a tuple with the RolloutRules field value
// and a boolean to check if the value has been set.
func (o *ConfigSettingValueModel) GetRolloutRulesOk() ([]RolloutRuleModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.RolloutRules, true
}

// SetRolloutRules sets field value
func (o *ConfigSettingValueModel) SetRolloutRules(v []RolloutRuleModel) {
	o.RolloutRules = v
}

// GetRolloutPercentageItems returns the RolloutPercentageItems field value
func (o *ConfigSettingValueModel) GetRolloutPercentageItems() []RolloutPercentageItemModel {
	if o == nil {
		var ret []RolloutPercentageItemModel
		return ret
	}

	return o.RolloutPercentageItems
}

// GetRolloutPercentageItemsOk returns a tuple with the RolloutPercentageItems field value
// and a boolean to check if the value has been set.
func (o *ConfigSettingValueModel) GetRolloutPercentageItemsOk() ([]RolloutPercentageItemModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.RolloutPercentageItems, true
}

// SetRolloutPercentageItems sets field value
func (o *ConfigSettingValueModel) SetRolloutPercentageItems(v []RolloutPercentageItemModel) {
	o.RolloutPercentageItems = v
}

// GetValue returns the Value field value
func (o *ConfigSettingValueModel) GetValue() SettingValueType {
	if o == nil {
		var ret SettingValueType
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ConfigSettingValueModel) GetValueOk() (*SettingValueType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ConfigSettingValueModel) SetValue(v SettingValueType) {
	o.Value = v
}

func (o ConfigSettingValueModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigSettingValueModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["setting"] = o.Setting
	toSerialize["updatedAt"] = o.UpdatedAt.Get()
	toSerialize["lastUpdaterUserEmail"] = o.LastUpdaterUserEmail.Get()
	toSerialize["lastUpdaterUserFullName"] = o.LastUpdaterUserFullName.Get()
	toSerialize["integrationLinks"] = o.IntegrationLinks
	toSerialize["settingTags"] = o.SettingTags
	toSerialize["rolloutRules"] = o.RolloutRules
	toSerialize["rolloutPercentageItems"] = o.RolloutPercentageItems
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigSettingValueModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"setting",
		"updatedAt",
		"lastUpdaterUserEmail",
		"lastUpdaterUserFullName",
		"integrationLinks",
		"settingTags",
		"rolloutRules",
		"rolloutPercentageItems",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigSettingValueModel := _ConfigSettingValueModel{}

	err = json.Unmarshal(data, &varConfigSettingValueModel)

	if err != nil {
		return err
	}

	*o = ConfigSettingValueModel(varConfigSettingValueModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "setting")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "lastUpdaterUserEmail")
		delete(additionalProperties, "lastUpdaterUserFullName")
		delete(additionalProperties, "integrationLinks")
		delete(additionalProperties, "settingTags")
		delete(additionalProperties, "rolloutRules")
		delete(additionalProperties, "rolloutPercentageItems")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigSettingValueModel struct {
	value *ConfigSettingValueModel
	isSet bool
}

func (v NullableConfigSettingValueModel) Get() *ConfigSettingValueModel {
	return v.value
}

func (v *NullableConfigSettingValueModel) Set(val *ConfigSettingValueModel) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigSettingValueModel) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigSettingValueModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigSettingValueModel(val *ConfigSettingValueModel) *NullableConfigSettingValueModel {
	return &NullableConfigSettingValueModel{value: val, isSet: true}
}

func (v NullableConfigSettingValueModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigSettingValueModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


