/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the SettingValueModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingValueModel{}

// SettingValueModel struct for SettingValueModel
type SettingValueModel struct {
	Setting SettingDataModel `json:"setting"`
	// The last updated date and time when the Feature Flag or Setting.
	UpdatedAt NullableTime `json:"updatedAt"`
	// The email of the user who last updated the Feature Flag or Setting.
	LastUpdaterUserEmail NullableString `json:"lastUpdaterUserEmail"`
	// The name of the user who last updated the Feature Flag or Setting.
	LastUpdaterUserFullName NullableString `json:"lastUpdaterUserFullName"`
	// The integration links attached to the Feature Flag or Setting.
	IntegrationLinks []IntegrationLinkModel `json:"integrationLinks"`
	// The tags attached to the Feature Flag or Setting.
	SettingTags []SettingTagModel `json:"settingTags"`
	// The targeting rule collection.
	RolloutRules []RolloutRuleModel `json:"rolloutRules"`
	// The percentage rule collection.
	RolloutPercentageItems []RolloutPercentageItemModel `json:"rolloutPercentageItems"`
	// The value to serve. It must respect the setting type. In some generated clients for strictly typed languages you may use double/float properties to handle integer values.
	Value SettingValueType `json:"value"`
	Config ConfigModel `json:"config"`
	Environment EnvironmentModel `json:"environment"`
	FeatureFlagLimitations FeatureFlagLimitations `json:"featureFlagLimitations"`
	ReadOnly bool `json:"readOnly"`
	AdditionalProperties map[string]interface{}
}

type _SettingValueModel SettingValueModel

// NewSettingValueModel instantiates a new SettingValueModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingValueModel(setting SettingDataModel, updatedAt NullableTime, lastUpdaterUserEmail NullableString, lastUpdaterUserFullName NullableString, integrationLinks []IntegrationLinkModel, settingTags []SettingTagModel, rolloutRules []RolloutRuleModel, rolloutPercentageItems []RolloutPercentageItemModel, value SettingValueType, config ConfigModel, environment EnvironmentModel, featureFlagLimitations FeatureFlagLimitations, readOnly bool) *SettingValueModel {
	this := SettingValueModel{}
	this.Setting = setting
	this.UpdatedAt = updatedAt
	this.LastUpdaterUserEmail = lastUpdaterUserEmail
	this.LastUpdaterUserFullName = lastUpdaterUserFullName
	this.IntegrationLinks = integrationLinks
	this.SettingTags = settingTags
	this.RolloutRules = rolloutRules
	this.RolloutPercentageItems = rolloutPercentageItems
	this.Value = value
	this.Config = config
	this.Environment = environment
	this.FeatureFlagLimitations = featureFlagLimitations
	this.ReadOnly = readOnly
	return &this
}

// NewSettingValueModelWithDefaults instantiates a new SettingValueModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingValueModelWithDefaults() *SettingValueModel {
	this := SettingValueModel{}
	return &this
}

// GetSetting returns the Setting field value
func (o *SettingValueModel) GetSetting() SettingDataModel {
	if o == nil {
		var ret SettingDataModel
		return ret
	}

	return o.Setting
}

// GetSettingOk returns a tuple with the Setting field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetSettingOk() (*SettingDataModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Setting, true
}

// SetSetting sets field value
func (o *SettingValueModel) SetSetting(v SettingDataModel) {
	o.Setting = v
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *SettingValueModel) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingValueModel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *SettingValueModel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// GetLastUpdaterUserEmail returns the LastUpdaterUserEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SettingValueModel) GetLastUpdaterUserEmail() string {
	if o == nil || o.LastUpdaterUserEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdaterUserEmail.Get()
}

// GetLastUpdaterUserEmailOk returns a tuple with the LastUpdaterUserEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingValueModel) GetLastUpdaterUserEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdaterUserEmail.Get(), o.LastUpdaterUserEmail.IsSet()
}

// SetLastUpdaterUserEmail sets field value
func (o *SettingValueModel) SetLastUpdaterUserEmail(v string) {
	o.LastUpdaterUserEmail.Set(&v)
}

// GetLastUpdaterUserFullName returns the LastUpdaterUserFullName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SettingValueModel) GetLastUpdaterUserFullName() string {
	if o == nil || o.LastUpdaterUserFullName.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdaterUserFullName.Get()
}

// GetLastUpdaterUserFullNameOk returns a tuple with the LastUpdaterUserFullName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingValueModel) GetLastUpdaterUserFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdaterUserFullName.Get(), o.LastUpdaterUserFullName.IsSet()
}

// SetLastUpdaterUserFullName sets field value
func (o *SettingValueModel) SetLastUpdaterUserFullName(v string) {
	o.LastUpdaterUserFullName.Set(&v)
}

// GetIntegrationLinks returns the IntegrationLinks field value
func (o *SettingValueModel) GetIntegrationLinks() []IntegrationLinkModel {
	if o == nil {
		var ret []IntegrationLinkModel
		return ret
	}

	return o.IntegrationLinks
}

// GetIntegrationLinksOk returns a tuple with the IntegrationLinks field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetIntegrationLinksOk() ([]IntegrationLinkModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntegrationLinks, true
}

// SetIntegrationLinks sets field value
func (o *SettingValueModel) SetIntegrationLinks(v []IntegrationLinkModel) {
	o.IntegrationLinks = v
}

// GetSettingTags returns the SettingTags field value
func (o *SettingValueModel) GetSettingTags() []SettingTagModel {
	if o == nil {
		var ret []SettingTagModel
		return ret
	}

	return o.SettingTags
}

// GetSettingTagsOk returns a tuple with the SettingTags field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetSettingTagsOk() ([]SettingTagModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.SettingTags, true
}

// SetSettingTags sets field value
func (o *SettingValueModel) SetSettingTags(v []SettingTagModel) {
	o.SettingTags = v
}

// GetRolloutRules returns the RolloutRules field value
func (o *SettingValueModel) GetRolloutRules() []RolloutRuleModel {
	if o == nil {
		var ret []RolloutRuleModel
		return ret
	}

	return o.RolloutRules
}

// GetRolloutRulesOk returns a tuple with the RolloutRules field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetRolloutRulesOk() ([]RolloutRuleModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.RolloutRules, true
}

// SetRolloutRules sets field value
func (o *SettingValueModel) SetRolloutRules(v []RolloutRuleModel) {
	o.RolloutRules = v
}

// GetRolloutPercentageItems returns the RolloutPercentageItems field value
func (o *SettingValueModel) GetRolloutPercentageItems() []RolloutPercentageItemModel {
	if o == nil {
		var ret []RolloutPercentageItemModel
		return ret
	}

	return o.RolloutPercentageItems
}

// GetRolloutPercentageItemsOk returns a tuple with the RolloutPercentageItems field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetRolloutPercentageItemsOk() ([]RolloutPercentageItemModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.RolloutPercentageItems, true
}

// SetRolloutPercentageItems sets field value
func (o *SettingValueModel) SetRolloutPercentageItems(v []RolloutPercentageItemModel) {
	o.RolloutPercentageItems = v
}

// GetValue returns the Value field value
func (o *SettingValueModel) GetValue() SettingValueType {
	if o == nil {
		var ret SettingValueType
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetValueOk() (*SettingValueType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SettingValueModel) SetValue(v SettingValueType) {
	o.Value = v
}

// GetConfig returns the Config field value
func (o *SettingValueModel) GetConfig() ConfigModel {
	if o == nil {
		var ret ConfigModel
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetConfigOk() (*ConfigModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *SettingValueModel) SetConfig(v ConfigModel) {
	o.Config = v
}

// GetEnvironment returns the Environment field value
func (o *SettingValueModel) GetEnvironment() EnvironmentModel {
	if o == nil {
		var ret EnvironmentModel
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetEnvironmentOk() (*EnvironmentModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *SettingValueModel) SetEnvironment(v EnvironmentModel) {
	o.Environment = v
}

// GetFeatureFlagLimitations returns the FeatureFlagLimitations field value
func (o *SettingValueModel) GetFeatureFlagLimitations() FeatureFlagLimitations {
	if o == nil {
		var ret FeatureFlagLimitations
		return ret
	}

	return o.FeatureFlagLimitations
}

// GetFeatureFlagLimitationsOk returns a tuple with the FeatureFlagLimitations field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetFeatureFlagLimitationsOk() (*FeatureFlagLimitations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeatureFlagLimitations, true
}

// SetFeatureFlagLimitations sets field value
func (o *SettingValueModel) SetFeatureFlagLimitations(v FeatureFlagLimitations) {
	o.FeatureFlagLimitations = v
}

// GetReadOnly returns the ReadOnly field value
func (o *SettingValueModel) GetReadOnly() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value
// and a boolean to check if the value has been set.
func (o *SettingValueModel) GetReadOnlyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReadOnly, true
}

// SetReadOnly sets field value
func (o *SettingValueModel) SetReadOnly(v bool) {
	o.ReadOnly = v
}

func (o SettingValueModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingValueModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["setting"] = o.Setting
	toSerialize["updatedAt"] = o.UpdatedAt.Get()
	toSerialize["lastUpdaterUserEmail"] = o.LastUpdaterUserEmail.Get()
	toSerialize["lastUpdaterUserFullName"] = o.LastUpdaterUserFullName.Get()
	toSerialize["integrationLinks"] = o.IntegrationLinks
	toSerialize["settingTags"] = o.SettingTags
	toSerialize["rolloutRules"] = o.RolloutRules
	toSerialize["rolloutPercentageItems"] = o.RolloutPercentageItems
	toSerialize["value"] = o.Value
	toSerialize["config"] = o.Config
	toSerialize["environment"] = o.Environment
	toSerialize["featureFlagLimitations"] = o.FeatureFlagLimitations
	toSerialize["readOnly"] = o.ReadOnly

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SettingValueModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"setting",
		"updatedAt",
		"lastUpdaterUserEmail",
		"lastUpdaterUserFullName",
		"integrationLinks",
		"settingTags",
		"rolloutRules",
		"rolloutPercentageItems",
		"value",
		"config",
		"environment",
		"featureFlagLimitations",
		"readOnly",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettingValueModel := _SettingValueModel{}

	err = json.Unmarshal(data, &varSettingValueModel)

	if err != nil {
		return err
	}

	*o = SettingValueModel(varSettingValueModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "setting")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "lastUpdaterUserEmail")
		delete(additionalProperties, "lastUpdaterUserFullName")
		delete(additionalProperties, "integrationLinks")
		delete(additionalProperties, "settingTags")
		delete(additionalProperties, "rolloutRules")
		delete(additionalProperties, "rolloutPercentageItems")
		delete(additionalProperties, "value")
		delete(additionalProperties, "config")
		delete(additionalProperties, "environment")
		delete(additionalProperties, "featureFlagLimitations")
		delete(additionalProperties, "readOnly")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSettingValueModel struct {
	value *SettingValueModel
	isSet bool
}

func (v NullableSettingValueModel) Get() *SettingValueModel {
	return v.value
}

func (v *NullableSettingValueModel) Set(val *SettingValueModel) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingValueModel) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingValueModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingValueModel(val *SettingValueModel) *NullableSettingValueModel {
	return &NullableSettingValueModel{value: val, isSet: true}
}

func (v NullableSettingValueModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingValueModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


