/*
ConfigCat Public Management API

**Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The purpose of this API is to access the ConfigCat platform programmatically.  You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.   The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  and JSON+HAL format. Do not use this API for accessing and evaluating feature flag values. Use the [SDKs instead](https://configcat.com/docs/sdk-reference/overview).   # OpenAPI Specification  The complete specification is publicly available here: [swagger.json](v1/swagger.json).  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
)

// checks if the JsonNodeOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonNodeOptions{}

// JsonNodeOptions struct for JsonNodeOptions
type JsonNodeOptions struct {
	PropertyNameCaseInsensitive *bool `json:"propertyNameCaseInsensitive,omitempty"`
}

// NewJsonNodeOptions instantiates a new JsonNodeOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonNodeOptions() *JsonNodeOptions {
	this := JsonNodeOptions{}
	return &this
}

// NewJsonNodeOptionsWithDefaults instantiates a new JsonNodeOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonNodeOptionsWithDefaults() *JsonNodeOptions {
	this := JsonNodeOptions{}
	return &this
}

// GetPropertyNameCaseInsensitive returns the PropertyNameCaseInsensitive field value if set, zero value otherwise.
func (o *JsonNodeOptions) GetPropertyNameCaseInsensitive() bool {
	if o == nil || IsNil(o.PropertyNameCaseInsensitive) {
		var ret bool
		return ret
	}
	return *o.PropertyNameCaseInsensitive
}

// GetPropertyNameCaseInsensitiveOk returns a tuple with the PropertyNameCaseInsensitive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonNodeOptions) GetPropertyNameCaseInsensitiveOk() (*bool, bool) {
	if o == nil || IsNil(o.PropertyNameCaseInsensitive) {
		return nil, false
	}
	return o.PropertyNameCaseInsensitive, true
}

// HasPropertyNameCaseInsensitive returns a boolean if a field has been set.
func (o *JsonNodeOptions) HasPropertyNameCaseInsensitive() bool {
	if o != nil && !IsNil(o.PropertyNameCaseInsensitive) {
		return true
	}

	return false
}

// SetPropertyNameCaseInsensitive gets a reference to the given bool and assigns it to the PropertyNameCaseInsensitive field.
func (o *JsonNodeOptions) SetPropertyNameCaseInsensitive(v bool) {
	o.PropertyNameCaseInsensitive = &v
}

func (o JsonNodeOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonNodeOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PropertyNameCaseInsensitive) {
		toSerialize["propertyNameCaseInsensitive"] = o.PropertyNameCaseInsensitive
	}
	return toSerialize, nil
}

type NullableJsonNodeOptions struct {
	value *JsonNodeOptions
	isSet bool
}

func (v NullableJsonNodeOptions) Get() *JsonNodeOptions {
	return v.value
}

func (v *NullableJsonNodeOptions) Set(val *JsonNodeOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonNodeOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonNodeOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonNodeOptions(val *JsonNodeOptions) *NullableJsonNodeOptions {
	return &NullableJsonNodeOptions{value: val, isSet: true}
}

func (v NullableJsonNodeOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonNodeOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


