/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ApproveRequiredEnvironmentModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveRequiredEnvironmentModel{}

// ApproveRequiredEnvironmentModel struct for ApproveRequiredEnvironmentModel
type ApproveRequiredEnvironmentModel struct {
	// Identifier of the Environment.
	EnvironmentId string `json:"environmentId"`
	// Indicates that a mandatory approval is required in this Environment before changes are applied.
	ApproveRequired bool `json:"approveRequired"`
	// Name of the Environment.
	EnvironmentName NullableString `json:"environmentName"`
	AdditionalProperties map[string]interface{}
}

type _ApproveRequiredEnvironmentModel ApproveRequiredEnvironmentModel

// NewApproveRequiredEnvironmentModel instantiates a new ApproveRequiredEnvironmentModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveRequiredEnvironmentModel(environmentId string, approveRequired bool, environmentName NullableString) *ApproveRequiredEnvironmentModel {
	this := ApproveRequiredEnvironmentModel{}
	this.EnvironmentId = environmentId
	this.ApproveRequired = approveRequired
	this.EnvironmentName = environmentName
	return &this
}

// NewApproveRequiredEnvironmentModelWithDefaults instantiates a new ApproveRequiredEnvironmentModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveRequiredEnvironmentModelWithDefaults() *ApproveRequiredEnvironmentModel {
	this := ApproveRequiredEnvironmentModel{}
	return &this
}

// GetEnvironmentId returns the EnvironmentId field value
func (o *ApproveRequiredEnvironmentModel) GetEnvironmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value
// and a boolean to check if the value has been set.
func (o *ApproveRequiredEnvironmentModel) GetEnvironmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentId, true
}

// SetEnvironmentId sets field value
func (o *ApproveRequiredEnvironmentModel) SetEnvironmentId(v string) {
	o.EnvironmentId = v
}

// GetApproveRequired returns the ApproveRequired field value
func (o *ApproveRequiredEnvironmentModel) GetApproveRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ApproveRequired
}

// GetApproveRequiredOk returns a tuple with the ApproveRequired field value
// and a boolean to check if the value has been set.
func (o *ApproveRequiredEnvironmentModel) GetApproveRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApproveRequired, true
}

// SetApproveRequired sets field value
func (o *ApproveRequiredEnvironmentModel) SetApproveRequired(v bool) {
	o.ApproveRequired = v
}

// GetEnvironmentName returns the EnvironmentName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ApproveRequiredEnvironmentModel) GetEnvironmentName() string {
	if o == nil || o.EnvironmentName.Get() == nil {
		var ret string
		return ret
	}

	return *o.EnvironmentName.Get()
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApproveRequiredEnvironmentModel) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvironmentName.Get(), o.EnvironmentName.IsSet()
}

// SetEnvironmentName sets field value
func (o *ApproveRequiredEnvironmentModel) SetEnvironmentName(v string) {
	o.EnvironmentName.Set(&v)
}

func (o ApproveRequiredEnvironmentModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveRequiredEnvironmentModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentId"] = o.EnvironmentId
	toSerialize["approveRequired"] = o.ApproveRequired
	toSerialize["environmentName"] = o.EnvironmentName.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApproveRequiredEnvironmentModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environmentId",
		"approveRequired",
		"environmentName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveRequiredEnvironmentModel := _ApproveRequiredEnvironmentModel{}

	err = json.Unmarshal(data, &varApproveRequiredEnvironmentModel)

	if err != nil {
		return err
	}

	*o = ApproveRequiredEnvironmentModel(varApproveRequiredEnvironmentModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "environmentId")
		delete(additionalProperties, "approveRequired")
		delete(additionalProperties, "environmentName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApproveRequiredEnvironmentModel struct {
	value *ApproveRequiredEnvironmentModel
	isSet bool
}

func (v NullableApproveRequiredEnvironmentModel) Get() *ApproveRequiredEnvironmentModel {
	return v.value
}

func (v *NullableApproveRequiredEnvironmentModel) Set(val *ApproveRequiredEnvironmentModel) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveRequiredEnvironmentModel) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveRequiredEnvironmentModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveRequiredEnvironmentModel(val *ApproveRequiredEnvironmentModel) *NullableApproveRequiredEnvironmentModel {
	return &NullableApproveRequiredEnvironmentModel{value: val, isSet: true}
}

func (v NullableApproveRequiredEnvironmentModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveRequiredEnvironmentModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


