/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://test-api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://test-api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://test-api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://test-api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SegmentModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SegmentModel{}

// SegmentModel struct for SegmentModel
type SegmentModel struct {
	Product ProductModel `json:"product"`
	// Identifier of the Segment.
	SegmentId string `json:"segmentId"`
	// Name of the Segment.
	Name string `json:"name"`
	// Description of the Segment.
	Description NullableString `json:"description"`
	// The email of the user who created the Segment.
	CreatorEmail NullableString `json:"creatorEmail"`
	// The name of the user who created the Segment.
	CreatorFullName NullableString `json:"creatorFullName"`
	// The date and time when the Segment was created.
	CreatedAt time.Time `json:"createdAt"`
	// The email of the user who last updated the Segment.
	LastUpdaterEmail NullableString `json:"lastUpdaterEmail"`
	// The name of the user who last updated the Segment.
	LastUpdaterFullName NullableString `json:"lastUpdaterFullName"`
	// The date and time when the Segment was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
	// The user's attribute the evaluation process must take into account.
	ComparisonAttribute string `json:"comparisonAttribute"`
	Comparator RolloutRuleComparator `json:"comparator"`
	// The value to compare with the given user attribute's value.
	ComparisonValue string `json:"comparisonValue"`
}

type _SegmentModel SegmentModel

// NewSegmentModel instantiates a new SegmentModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSegmentModel(product ProductModel, segmentId string, name string, description NullableString, creatorEmail NullableString, creatorFullName NullableString, createdAt time.Time, lastUpdaterEmail NullableString, lastUpdaterFullName NullableString, updatedAt time.Time, comparisonAttribute string, comparator RolloutRuleComparator, comparisonValue string) *SegmentModel {
	this := SegmentModel{}
	this.Product = product
	this.SegmentId = segmentId
	this.Name = name
	this.Description = description
	this.CreatorEmail = creatorEmail
	this.CreatorFullName = creatorFullName
	this.CreatedAt = createdAt
	this.LastUpdaterEmail = lastUpdaterEmail
	this.LastUpdaterFullName = lastUpdaterFullName
	this.UpdatedAt = updatedAt
	this.ComparisonAttribute = comparisonAttribute
	this.Comparator = comparator
	this.ComparisonValue = comparisonValue
	return &this
}

// NewSegmentModelWithDefaults instantiates a new SegmentModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSegmentModelWithDefaults() *SegmentModel {
	this := SegmentModel{}
	return &this
}

// GetProduct returns the Product field value
func (o *SegmentModel) GetProduct() ProductModel {
	if o == nil {
		var ret ProductModel
		return ret
	}

	return o.Product
}

// GetProductOk returns a tuple with the Product field value
// and a boolean to check if the value has been set.
func (o *SegmentModel) GetProductOk() (*ProductModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Product, true
}

// SetProduct sets field value
func (o *SegmentModel) SetProduct(v ProductModel) {
	o.Product = v
}

// GetSegmentId returns the SegmentId field value
func (o *SegmentModel) GetSegmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SegmentId
}

// GetSegmentIdOk returns a tuple with the SegmentId field value
// and a boolean to check if the value has been set.
func (o *SegmentModel) GetSegmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SegmentId, true
}

// SetSegmentId sets field value
func (o *SegmentModel) SetSegmentId(v string) {
	o.SegmentId = v
}

// GetName returns the Name field value
func (o *SegmentModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SegmentModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SegmentModel) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SegmentModel) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *SegmentModel) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetCreatorEmail returns the CreatorEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SegmentModel) GetCreatorEmail() string {
	if o == nil || o.CreatorEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatorEmail.Get()
}

// GetCreatorEmailOk returns a tuple with the CreatorEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentModel) GetCreatorEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatorEmail.Get(), o.CreatorEmail.IsSet()
}

// SetCreatorEmail sets field value
func (o *SegmentModel) SetCreatorEmail(v string) {
	o.CreatorEmail.Set(&v)
}

// GetCreatorFullName returns the CreatorFullName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SegmentModel) GetCreatorFullName() string {
	if o == nil || o.CreatorFullName.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatorFullName.Get()
}

// GetCreatorFullNameOk returns a tuple with the CreatorFullName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentModel) GetCreatorFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatorFullName.Get(), o.CreatorFullName.IsSet()
}

// SetCreatorFullName sets field value
func (o *SegmentModel) SetCreatorFullName(v string) {
	o.CreatorFullName.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *SegmentModel) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SegmentModel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SegmentModel) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetLastUpdaterEmail returns the LastUpdaterEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SegmentModel) GetLastUpdaterEmail() string {
	if o == nil || o.LastUpdaterEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdaterEmail.Get()
}

// GetLastUpdaterEmailOk returns a tuple with the LastUpdaterEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentModel) GetLastUpdaterEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdaterEmail.Get(), o.LastUpdaterEmail.IsSet()
}

// SetLastUpdaterEmail sets field value
func (o *SegmentModel) SetLastUpdaterEmail(v string) {
	o.LastUpdaterEmail.Set(&v)
}

// GetLastUpdaterFullName returns the LastUpdaterFullName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SegmentModel) GetLastUpdaterFullName() string {
	if o == nil || o.LastUpdaterFullName.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdaterFullName.Get()
}

// GetLastUpdaterFullNameOk returns a tuple with the LastUpdaterFullName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentModel) GetLastUpdaterFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdaterFullName.Get(), o.LastUpdaterFullName.IsSet()
}

// SetLastUpdaterFullName sets field value
func (o *SegmentModel) SetLastUpdaterFullName(v string) {
	o.LastUpdaterFullName.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SegmentModel) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SegmentModel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SegmentModel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetComparisonAttribute returns the ComparisonAttribute field value
func (o *SegmentModel) GetComparisonAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComparisonAttribute
}

// GetComparisonAttributeOk returns a tuple with the ComparisonAttribute field value
// and a boolean to check if the value has been set.
func (o *SegmentModel) GetComparisonAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComparisonAttribute, true
}

// SetComparisonAttribute sets field value
func (o *SegmentModel) SetComparisonAttribute(v string) {
	o.ComparisonAttribute = v
}

// GetComparator returns the Comparator field value
func (o *SegmentModel) GetComparator() RolloutRuleComparator {
	if o == nil {
		var ret RolloutRuleComparator
		return ret
	}

	return o.Comparator
}

// GetComparatorOk returns a tuple with the Comparator field value
// and a boolean to check if the value has been set.
func (o *SegmentModel) GetComparatorOk() (*RolloutRuleComparator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comparator, true
}

// SetComparator sets field value
func (o *SegmentModel) SetComparator(v RolloutRuleComparator) {
	o.Comparator = v
}

// GetComparisonValue returns the ComparisonValue field value
func (o *SegmentModel) GetComparisonValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComparisonValue
}

// GetComparisonValueOk returns a tuple with the ComparisonValue field value
// and a boolean to check if the value has been set.
func (o *SegmentModel) GetComparisonValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComparisonValue, true
}

// SetComparisonValue sets field value
func (o *SegmentModel) SetComparisonValue(v string) {
	o.ComparisonValue = v
}

func (o SegmentModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SegmentModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["product"] = o.Product
	toSerialize["segmentId"] = o.SegmentId
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description.Get()
	toSerialize["creatorEmail"] = o.CreatorEmail.Get()
	toSerialize["creatorFullName"] = o.CreatorFullName.Get()
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["lastUpdaterEmail"] = o.LastUpdaterEmail.Get()
	toSerialize["lastUpdaterFullName"] = o.LastUpdaterFullName.Get()
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["comparisonAttribute"] = o.ComparisonAttribute
	toSerialize["comparator"] = o.Comparator
	toSerialize["comparisonValue"] = o.ComparisonValue
	return toSerialize, nil
}

func (o *SegmentModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"product",
		"segmentId",
		"name",
		"description",
		"creatorEmail",
		"creatorFullName",
		"createdAt",
		"lastUpdaterEmail",
		"lastUpdaterFullName",
		"updatedAt",
		"comparisonAttribute",
		"comparator",
		"comparisonValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSegmentModel := _SegmentModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSegmentModel)

	if err != nil {
		return err
	}

	*o = SegmentModel(varSegmentModel)

	return err
}

type NullableSegmentModel struct {
	value *SegmentModel
	isSet bool
}

func (v NullableSegmentModel) Get() *SegmentModel {
	return v.value
}

func (v *NullableSegmentModel) Set(val *SegmentModel) {
	v.value = val
	v.isSet = true
}

func (v NullableSegmentModel) IsSet() bool {
	return v.isSet
}

func (v *NullableSegmentModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSegmentModel(val *SegmentModel) *NullableSegmentModel {
	return &NullableSegmentModel{value: val, isSet: true}
}

func (v NullableSegmentModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSegmentModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


