/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DeletedSettingModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletedSettingModel{}

// DeletedSettingModel struct for DeletedSettingModel
type DeletedSettingModel struct {
	// Key of the Feature Flag or Setting.
	Key string `json:"key"`
	// Name of the Feature Flag or Setting.
	Name string `json:"name"`
	// Description of the Feature Flag or Setting.
	Hint NullableString `json:"hint"`
	SettingType SettingType `json:"settingType"`
	AdditionalProperties map[string]interface{}
}

type _DeletedSettingModel DeletedSettingModel

// NewDeletedSettingModel instantiates a new DeletedSettingModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletedSettingModel(key string, name string, hint NullableString, settingType SettingType) *DeletedSettingModel {
	this := DeletedSettingModel{}
	this.Key = key
	this.Name = name
	this.Hint = hint
	this.SettingType = settingType
	return &this
}

// NewDeletedSettingModelWithDefaults instantiates a new DeletedSettingModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletedSettingModelWithDefaults() *DeletedSettingModel {
	this := DeletedSettingModel{}
	return &this
}

// GetKey returns the Key field value
func (o *DeletedSettingModel) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *DeletedSettingModel) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *DeletedSettingModel) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *DeletedSettingModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeletedSettingModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeletedSettingModel) SetName(v string) {
	o.Name = v
}

// GetHint returns the Hint field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DeletedSettingModel) GetHint() string {
	if o == nil || o.Hint.Get() == nil {
		var ret string
		return ret
	}

	return *o.Hint.Get()
}

// GetHintOk returns a tuple with the Hint field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeletedSettingModel) GetHintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hint.Get(), o.Hint.IsSet()
}

// SetHint sets field value
func (o *DeletedSettingModel) SetHint(v string) {
	o.Hint.Set(&v)
}

// GetSettingType returns the SettingType field value
func (o *DeletedSettingModel) GetSettingType() SettingType {
	if o == nil {
		var ret SettingType
		return ret
	}

	return o.SettingType
}

// GetSettingTypeOk returns a tuple with the SettingType field value
// and a boolean to check if the value has been set.
func (o *DeletedSettingModel) GetSettingTypeOk() (*SettingType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettingType, true
}

// SetSettingType sets field value
func (o *DeletedSettingModel) SetSettingType(v SettingType) {
	o.SettingType = v
}

func (o DeletedSettingModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletedSettingModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	toSerialize["hint"] = o.Hint.Get()
	toSerialize["settingType"] = o.SettingType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeletedSettingModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"name",
		"hint",
		"settingType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletedSettingModel := _DeletedSettingModel{}

	err = json.Unmarshal(data, &varDeletedSettingModel)

	if err != nil {
		return err
	}

	*o = DeletedSettingModel(varDeletedSettingModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "name")
		delete(additionalProperties, "hint")
		delete(additionalProperties, "settingType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeletedSettingModel struct {
	value *DeletedSettingModel
	isSet bool
}

func (v NullableDeletedSettingModel) Get() *DeletedSettingModel {
	return v.value
}

func (v *NullableDeletedSettingModel) Set(val *DeletedSettingModel) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletedSettingModel) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletedSettingModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletedSettingModel(val *DeletedSettingModel) *NullableDeletedSettingModel {
	return &NullableDeletedSettingModel{value: val, isSet: true}
}

func (v NullableDeletedSettingModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletedSettingModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


