/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateOrUpdateWebhookNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateWebhookNotification{}

// CreateOrUpdateWebhookNotification The preferences related to a connection, including polling intervals and webhook proxy configurations.
type CreateOrUpdateWebhookNotification struct {
	// The webhook proxy URL for receiving config JSON change notifications.
	WebhookProxyUrl string `json:"webhookProxyUrl"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrUpdateWebhookNotification CreateOrUpdateWebhookNotification

// NewCreateOrUpdateWebhookNotification instantiates a new CreateOrUpdateWebhookNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateWebhookNotification(webhookProxyUrl string) *CreateOrUpdateWebhookNotification {
	this := CreateOrUpdateWebhookNotification{}
	this.WebhookProxyUrl = webhookProxyUrl
	return &this
}

// NewCreateOrUpdateWebhookNotificationWithDefaults instantiates a new CreateOrUpdateWebhookNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateWebhookNotificationWithDefaults() *CreateOrUpdateWebhookNotification {
	this := CreateOrUpdateWebhookNotification{}
	return &this
}

// GetWebhookProxyUrl returns the WebhookProxyUrl field value
func (o *CreateOrUpdateWebhookNotification) GetWebhookProxyUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookProxyUrl
}

// GetWebhookProxyUrlOk returns a tuple with the WebhookProxyUrl field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateWebhookNotification) GetWebhookProxyUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookProxyUrl, true
}

// SetWebhookProxyUrl sets field value
func (o *CreateOrUpdateWebhookNotification) SetWebhookProxyUrl(v string) {
	o.WebhookProxyUrl = v
}

func (o CreateOrUpdateWebhookNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateWebhookNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["webhookProxyUrl"] = o.WebhookProxyUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrUpdateWebhookNotification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"webhookProxyUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrUpdateWebhookNotification := _CreateOrUpdateWebhookNotification{}

	err = json.Unmarshal(data, &varCreateOrUpdateWebhookNotification)

	if err != nil {
		return err
	}

	*o = CreateOrUpdateWebhookNotification(varCreateOrUpdateWebhookNotification)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "webhookProxyUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrUpdateWebhookNotification struct {
	value *CreateOrUpdateWebhookNotification
	isSet bool
}

func (v NullableCreateOrUpdateWebhookNotification) Get() *CreateOrUpdateWebhookNotification {
	return v.value
}

func (v *NullableCreateOrUpdateWebhookNotification) Set(val *CreateOrUpdateWebhookNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateWebhookNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateWebhookNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateWebhookNotification(val *CreateOrUpdateWebhookNotification) *NullableCreateOrUpdateWebhookNotification {
	return &NullableCreateOrUpdateWebhookNotification{value: val, isSet: true}
}

func (v NullableCreateOrUpdateWebhookNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateWebhookNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


