/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PredefinedVariationsWithUsagesModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PredefinedVariationsWithUsagesModel{}

// PredefinedVariationsWithUsagesModel struct for PredefinedVariationsWithUsagesModel
type PredefinedVariationsWithUsagesModel struct {
	// Key of the Feature Flag or Setting.
	SettingKey string `json:"settingKey"`
	SettingType SettingType `json:"settingType"`
	// The Feature Flag or Setting's Variations.
	PredefinedVariations []PredefinedVariationWithUsagesModel `json:"predefinedVariations"`
	// The Environment descriptors for the Variations' usages.
	Environments []PredefinedVariationEnvironmentModel `json:"environments"`
	// The maximum number of predefined variations allowed for the Feature Flag or Setting.
	MaxPredefinedVariations int32 `json:"maxPredefinedVariations"`
	AdditionalProperties map[string]interface{}
}

type _PredefinedVariationsWithUsagesModel PredefinedVariationsWithUsagesModel

// NewPredefinedVariationsWithUsagesModel instantiates a new PredefinedVariationsWithUsagesModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPredefinedVariationsWithUsagesModel(settingKey string, settingType SettingType, predefinedVariations []PredefinedVariationWithUsagesModel, environments []PredefinedVariationEnvironmentModel, maxPredefinedVariations int32) *PredefinedVariationsWithUsagesModel {
	this := PredefinedVariationsWithUsagesModel{}
	this.SettingKey = settingKey
	this.SettingType = settingType
	this.PredefinedVariations = predefinedVariations
	this.Environments = environments
	this.MaxPredefinedVariations = maxPredefinedVariations
	return &this
}

// NewPredefinedVariationsWithUsagesModelWithDefaults instantiates a new PredefinedVariationsWithUsagesModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPredefinedVariationsWithUsagesModelWithDefaults() *PredefinedVariationsWithUsagesModel {
	this := PredefinedVariationsWithUsagesModel{}
	return &this
}

// GetSettingKey returns the SettingKey field value
func (o *PredefinedVariationsWithUsagesModel) GetSettingKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SettingKey
}

// GetSettingKeyOk returns a tuple with the SettingKey field value
// and a boolean to check if the value has been set.
func (o *PredefinedVariationsWithUsagesModel) GetSettingKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettingKey, true
}

// SetSettingKey sets field value
func (o *PredefinedVariationsWithUsagesModel) SetSettingKey(v string) {
	o.SettingKey = v
}

// GetSettingType returns the SettingType field value
func (o *PredefinedVariationsWithUsagesModel) GetSettingType() SettingType {
	if o == nil {
		var ret SettingType
		return ret
	}

	return o.SettingType
}

// GetSettingTypeOk returns a tuple with the SettingType field value
// and a boolean to check if the value has been set.
func (o *PredefinedVariationsWithUsagesModel) GetSettingTypeOk() (*SettingType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettingType, true
}

// SetSettingType sets field value
func (o *PredefinedVariationsWithUsagesModel) SetSettingType(v SettingType) {
	o.SettingType = v
}

// GetPredefinedVariations returns the PredefinedVariations field value
func (o *PredefinedVariationsWithUsagesModel) GetPredefinedVariations() []PredefinedVariationWithUsagesModel {
	if o == nil {
		var ret []PredefinedVariationWithUsagesModel
		return ret
	}

	return o.PredefinedVariations
}

// GetPredefinedVariationsOk returns a tuple with the PredefinedVariations field value
// and a boolean to check if the value has been set.
func (o *PredefinedVariationsWithUsagesModel) GetPredefinedVariationsOk() ([]PredefinedVariationWithUsagesModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.PredefinedVariations, true
}

// SetPredefinedVariations sets field value
func (o *PredefinedVariationsWithUsagesModel) SetPredefinedVariations(v []PredefinedVariationWithUsagesModel) {
	o.PredefinedVariations = v
}

// GetEnvironments returns the Environments field value
func (o *PredefinedVariationsWithUsagesModel) GetEnvironments() []PredefinedVariationEnvironmentModel {
	if o == nil {
		var ret []PredefinedVariationEnvironmentModel
		return ret
	}

	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value
// and a boolean to check if the value has been set.
func (o *PredefinedVariationsWithUsagesModel) GetEnvironmentsOk() ([]PredefinedVariationEnvironmentModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environments, true
}

// SetEnvironments sets field value
func (o *PredefinedVariationsWithUsagesModel) SetEnvironments(v []PredefinedVariationEnvironmentModel) {
	o.Environments = v
}

// GetMaxPredefinedVariations returns the MaxPredefinedVariations field value
func (o *PredefinedVariationsWithUsagesModel) GetMaxPredefinedVariations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxPredefinedVariations
}

// GetMaxPredefinedVariationsOk returns a tuple with the MaxPredefinedVariations field value
// and a boolean to check if the value has been set.
func (o *PredefinedVariationsWithUsagesModel) GetMaxPredefinedVariationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxPredefinedVariations, true
}

// SetMaxPredefinedVariations sets field value
func (o *PredefinedVariationsWithUsagesModel) SetMaxPredefinedVariations(v int32) {
	o.MaxPredefinedVariations = v
}

func (o PredefinedVariationsWithUsagesModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PredefinedVariationsWithUsagesModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["settingKey"] = o.SettingKey
	toSerialize["settingType"] = o.SettingType
	toSerialize["predefinedVariations"] = o.PredefinedVariations
	toSerialize["environments"] = o.Environments
	toSerialize["maxPredefinedVariations"] = o.MaxPredefinedVariations

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PredefinedVariationsWithUsagesModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"settingKey",
		"settingType",
		"predefinedVariations",
		"environments",
		"maxPredefinedVariations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPredefinedVariationsWithUsagesModel := _PredefinedVariationsWithUsagesModel{}

	err = json.Unmarshal(data, &varPredefinedVariationsWithUsagesModel)

	if err != nil {
		return err
	}

	*o = PredefinedVariationsWithUsagesModel(varPredefinedVariationsWithUsagesModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "settingKey")
		delete(additionalProperties, "settingType")
		delete(additionalProperties, "predefinedVariations")
		delete(additionalProperties, "environments")
		delete(additionalProperties, "maxPredefinedVariations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePredefinedVariationsWithUsagesModel struct {
	value *PredefinedVariationsWithUsagesModel
	isSet bool
}

func (v NullablePredefinedVariationsWithUsagesModel) Get() *PredefinedVariationsWithUsagesModel {
	return v.value
}

func (v *NullablePredefinedVariationsWithUsagesModel) Set(val *PredefinedVariationsWithUsagesModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePredefinedVariationsWithUsagesModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePredefinedVariationsWithUsagesModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePredefinedVariationsWithUsagesModel(val *PredefinedVariationsWithUsagesModel) *NullablePredefinedVariationsWithUsagesModel {
	return &NullablePredefinedVariationsWithUsagesModel{value: val, isSet: true}
}

func (v NullablePredefinedVariationsWithUsagesModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePredefinedVariationsWithUsagesModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


