/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AuditLogItemModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditLogItemModel{}

// AuditLogItemModel struct for AuditLogItemModel
type AuditLogItemModel struct {
	AuditLogId int64 `json:"auditLogId"`
	AuditLogDateTime time.Time `json:"auditLogDateTime"`
	AuditLogTypeEnum AuditLogType `json:"auditLogTypeEnum"`
	Truncated bool `json:"truncated"`
	ModelVersion int32 `json:"modelVersion"`
	AuditLogType string `json:"auditLogType"`
	UserEmail NullableString `json:"userEmail"`
	UserName string `json:"userName"`
	Where string `json:"where"`
	Why NullableString `json:"why"`
	ActionTarget string `json:"actionTarget"`
	Details string `json:"details"`
	AdditionalProperties map[string]interface{}
}

type _AuditLogItemModel AuditLogItemModel

// NewAuditLogItemModel instantiates a new AuditLogItemModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditLogItemModel(auditLogId int64, auditLogDateTime time.Time, auditLogTypeEnum AuditLogType, truncated bool, modelVersion int32, auditLogType string, userEmail NullableString, userName string, where string, why NullableString, actionTarget string, details string) *AuditLogItemModel {
	this := AuditLogItemModel{}
	this.AuditLogId = auditLogId
	this.AuditLogDateTime = auditLogDateTime
	this.AuditLogTypeEnum = auditLogTypeEnum
	this.Truncated = truncated
	this.ModelVersion = modelVersion
	this.AuditLogType = auditLogType
	this.UserEmail = userEmail
	this.UserName = userName
	this.Where = where
	this.Why = why
	this.ActionTarget = actionTarget
	this.Details = details
	return &this
}

// NewAuditLogItemModelWithDefaults instantiates a new AuditLogItemModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditLogItemModelWithDefaults() *AuditLogItemModel {
	this := AuditLogItemModel{}
	return &this
}

// GetAuditLogId returns the AuditLogId field value
func (o *AuditLogItemModel) GetAuditLogId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AuditLogId
}

// GetAuditLogIdOk returns a tuple with the AuditLogId field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetAuditLogIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditLogId, true
}

// SetAuditLogId sets field value
func (o *AuditLogItemModel) SetAuditLogId(v int64) {
	o.AuditLogId = v
}

// GetAuditLogDateTime returns the AuditLogDateTime field value
func (o *AuditLogItemModel) GetAuditLogDateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AuditLogDateTime
}

// GetAuditLogDateTimeOk returns a tuple with the AuditLogDateTime field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetAuditLogDateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditLogDateTime, true
}

// SetAuditLogDateTime sets field value
func (o *AuditLogItemModel) SetAuditLogDateTime(v time.Time) {
	o.AuditLogDateTime = v
}

// GetAuditLogTypeEnum returns the AuditLogTypeEnum field value
func (o *AuditLogItemModel) GetAuditLogTypeEnum() AuditLogType {
	if o == nil {
		var ret AuditLogType
		return ret
	}

	return o.AuditLogTypeEnum
}

// GetAuditLogTypeEnumOk returns a tuple with the AuditLogTypeEnum field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetAuditLogTypeEnumOk() (*AuditLogType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditLogTypeEnum, true
}

// SetAuditLogTypeEnum sets field value
func (o *AuditLogItemModel) SetAuditLogTypeEnum(v AuditLogType) {
	o.AuditLogTypeEnum = v
}

// GetTruncated returns the Truncated field value
func (o *AuditLogItemModel) GetTruncated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Truncated
}

// GetTruncatedOk returns a tuple with the Truncated field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetTruncatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Truncated, true
}

// SetTruncated sets field value
func (o *AuditLogItemModel) SetTruncated(v bool) {
	o.Truncated = v
}

// GetModelVersion returns the ModelVersion field value
func (o *AuditLogItemModel) GetModelVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ModelVersion
}

// GetModelVersionOk returns a tuple with the ModelVersion field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetModelVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelVersion, true
}

// SetModelVersion sets field value
func (o *AuditLogItemModel) SetModelVersion(v int32) {
	o.ModelVersion = v
}

// GetAuditLogType returns the AuditLogType field value
func (o *AuditLogItemModel) GetAuditLogType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuditLogType
}

// GetAuditLogTypeOk returns a tuple with the AuditLogType field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetAuditLogTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuditLogType, true
}

// SetAuditLogType sets field value
func (o *AuditLogItemModel) SetAuditLogType(v string) {
	o.AuditLogType = v
}

// GetUserEmail returns the UserEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditLogItemModel) GetUserEmail() string {
	if o == nil || o.UserEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.UserEmail.Get()
}

// GetUserEmailOk returns a tuple with the UserEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditLogItemModel) GetUserEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserEmail.Get(), o.UserEmail.IsSet()
}

// SetUserEmail sets field value
func (o *AuditLogItemModel) SetUserEmail(v string) {
	o.UserEmail.Set(&v)
}

// GetUserName returns the UserName field value
func (o *AuditLogItemModel) GetUserName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserName, true
}

// SetUserName sets field value
func (o *AuditLogItemModel) SetUserName(v string) {
	o.UserName = v
}

// GetWhere returns the Where field value
func (o *AuditLogItemModel) GetWhere() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Where
}

// GetWhereOk returns a tuple with the Where field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetWhereOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Where, true
}

// SetWhere sets field value
func (o *AuditLogItemModel) SetWhere(v string) {
	o.Where = v
}

// GetWhy returns the Why field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AuditLogItemModel) GetWhy() string {
	if o == nil || o.Why.Get() == nil {
		var ret string
		return ret
	}

	return *o.Why.Get()
}

// GetWhyOk returns a tuple with the Why field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuditLogItemModel) GetWhyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Why.Get(), o.Why.IsSet()
}

// SetWhy sets field value
func (o *AuditLogItemModel) SetWhy(v string) {
	o.Why.Set(&v)
}

// GetActionTarget returns the ActionTarget field value
func (o *AuditLogItemModel) GetActionTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActionTarget
}

// GetActionTargetOk returns a tuple with the ActionTarget field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetActionTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionTarget, true
}

// SetActionTarget sets field value
func (o *AuditLogItemModel) SetActionTarget(v string) {
	o.ActionTarget = v
}

// GetDetails returns the Details field value
func (o *AuditLogItemModel) GetDetails() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *AuditLogItemModel) GetDetailsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *AuditLogItemModel) SetDetails(v string) {
	o.Details = v
}

func (o AuditLogItemModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditLogItemModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auditLogId"] = o.AuditLogId
	toSerialize["auditLogDateTime"] = o.AuditLogDateTime
	toSerialize["auditLogTypeEnum"] = o.AuditLogTypeEnum
	toSerialize["truncated"] = o.Truncated
	toSerialize["modelVersion"] = o.ModelVersion
	toSerialize["auditLogType"] = o.AuditLogType
	toSerialize["userEmail"] = o.UserEmail.Get()
	toSerialize["userName"] = o.UserName
	toSerialize["where"] = o.Where
	toSerialize["why"] = o.Why.Get()
	toSerialize["actionTarget"] = o.ActionTarget
	toSerialize["details"] = o.Details

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuditLogItemModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auditLogId",
		"auditLogDateTime",
		"auditLogTypeEnum",
		"truncated",
		"modelVersion",
		"auditLogType",
		"userEmail",
		"userName",
		"where",
		"why",
		"actionTarget",
		"details",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditLogItemModel := _AuditLogItemModel{}

	err = json.Unmarshal(data, &varAuditLogItemModel)

	if err != nil {
		return err
	}

	*o = AuditLogItemModel(varAuditLogItemModel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "auditLogId")
		delete(additionalProperties, "auditLogDateTime")
		delete(additionalProperties, "auditLogTypeEnum")
		delete(additionalProperties, "truncated")
		delete(additionalProperties, "modelVersion")
		delete(additionalProperties, "auditLogType")
		delete(additionalProperties, "userEmail")
		delete(additionalProperties, "userName")
		delete(additionalProperties, "where")
		delete(additionalProperties, "why")
		delete(additionalProperties, "actionTarget")
		delete(additionalProperties, "details")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuditLogItemModel struct {
	value *AuditLogItemModel
	isSet bool
}

func (v NullableAuditLogItemModel) Get() *AuditLogItemModel {
	return v.value
}

func (v *NullableAuditLogItemModel) Set(val *AuditLogItemModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditLogItemModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditLogItemModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditLogItemModel(val *AuditLogItemModel) *NullableAuditLogItemModel {
	return &NullableAuditLogItemModel{value: val, isSet: true}
}

func (v NullableAuditLogItemModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditLogItemModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


