/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://test-api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://test-api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://test-api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://test-api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PermissionGroupModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionGroupModel{}

// PermissionGroupModel struct for PermissionGroupModel
type PermissionGroupModel struct {
	// Identifier of the Permission Group.
	PermissionGroupId int64 `json:"permissionGroupId"`
	// Name of the Permission Group.
	Name string `json:"name"`
	// Group members can manage team members.
	CanManageMembers bool `json:"canManageMembers"`
	// Group members can create/update Configs.
	CanCreateOrUpdateConfig bool `json:"canCreateOrUpdateConfig"`
	// Group members can delete Configs.
	CanDeleteConfig bool `json:"canDeleteConfig"`
	// Group members can create/update Environments.
	CanCreateOrUpdateEnvironment bool `json:"canCreateOrUpdateEnvironment"`
	// Group members can delete Environments.
	CanDeleteEnvironment bool `json:"canDeleteEnvironment"`
	// Group members can create/update Feature Flags and Settings.
	CanCreateOrUpdateSetting bool `json:"canCreateOrUpdateSetting"`
	// Group members can attach/detach Tags to Feature Flags and Settings.
	CanTagSetting bool `json:"canTagSetting"`
	// Group members can delete Feature Flags and Settings.
	CanDeleteSetting bool `json:"canDeleteSetting"`
	// Group members can create/update Tags.
	CanCreateOrUpdateTag bool `json:"canCreateOrUpdateTag"`
	// Group members can delete Tags.
	CanDeleteTag bool `json:"canDeleteTag"`
	// Group members can create/update/delete Webhooks.
	CanManageWebhook bool `json:"canManageWebhook"`
	// Group members can use the export/import feature.
	CanUseExportImport bool `json:"canUseExportImport"`
	// Group members can update Product preferences.
	CanManageProductPreferences bool `json:"canManageProductPreferences"`
	// Group members can add and configure integrations.
	CanManageIntegrations bool `json:"canManageIntegrations"`
	// Group members has access to SDK keys.
	CanViewSdkKey bool `json:"canViewSdkKey"`
	// Group members can rotate SDK keys.
	CanRotateSdkKey bool `json:"canRotateSdkKey"`
	// Group members can create/update Segments.
	CanCreateOrUpdateSegments bool `json:"canCreateOrUpdateSegments"`
	// Group members can delete Segments.
	CanDeleteSegments bool `json:"canDeleteSegments"`
	// Group members has access to audit logs.
	CanViewProductAuditLog bool `json:"canViewProductAuditLog"`
	// Group members has access to product statistics.
	CanViewProductStatistics bool `json:"canViewProductStatistics"`
	// Group members can disable two-factor authentication for other members.
	CanDisable2FA bool `json:"canDisable2FA"`
	AccessType AccessType `json:"accessType"`
	NewEnvironmentAccessType EnvironmentAccessType `json:"newEnvironmentAccessType"`
	// List of environment specific permissions.
	EnvironmentAccesses []EnvironmentAccessModel `json:"environmentAccesses"`
	Product ProductModel `json:"product"`
}

type _PermissionGroupModel PermissionGroupModel

// NewPermissionGroupModel instantiates a new PermissionGroupModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionGroupModel(permissionGroupId int64, name string, canManageMembers bool, canCreateOrUpdateConfig bool, canDeleteConfig bool, canCreateOrUpdateEnvironment bool, canDeleteEnvironment bool, canCreateOrUpdateSetting bool, canTagSetting bool, canDeleteSetting bool, canCreateOrUpdateTag bool, canDeleteTag bool, canManageWebhook bool, canUseExportImport bool, canManageProductPreferences bool, canManageIntegrations bool, canViewSdkKey bool, canRotateSdkKey bool, canCreateOrUpdateSegments bool, canDeleteSegments bool, canViewProductAuditLog bool, canViewProductStatistics bool, canDisable2FA bool, accessType AccessType, newEnvironmentAccessType EnvironmentAccessType, environmentAccesses []EnvironmentAccessModel, product ProductModel) *PermissionGroupModel {
	this := PermissionGroupModel{}
	this.PermissionGroupId = permissionGroupId
	this.Name = name
	this.CanManageMembers = canManageMembers
	this.CanCreateOrUpdateConfig = canCreateOrUpdateConfig
	this.CanDeleteConfig = canDeleteConfig
	this.CanCreateOrUpdateEnvironment = canCreateOrUpdateEnvironment
	this.CanDeleteEnvironment = canDeleteEnvironment
	this.CanCreateOrUpdateSetting = canCreateOrUpdateSetting
	this.CanTagSetting = canTagSetting
	this.CanDeleteSetting = canDeleteSetting
	this.CanCreateOrUpdateTag = canCreateOrUpdateTag
	this.CanDeleteTag = canDeleteTag
	this.CanManageWebhook = canManageWebhook
	this.CanUseExportImport = canUseExportImport
	this.CanManageProductPreferences = canManageProductPreferences
	this.CanManageIntegrations = canManageIntegrations
	this.CanViewSdkKey = canViewSdkKey
	this.CanRotateSdkKey = canRotateSdkKey
	this.CanCreateOrUpdateSegments = canCreateOrUpdateSegments
	this.CanDeleteSegments = canDeleteSegments
	this.CanViewProductAuditLog = canViewProductAuditLog
	this.CanViewProductStatistics = canViewProductStatistics
	this.CanDisable2FA = canDisable2FA
	this.AccessType = accessType
	this.NewEnvironmentAccessType = newEnvironmentAccessType
	this.EnvironmentAccesses = environmentAccesses
	this.Product = product
	return &this
}

// NewPermissionGroupModelWithDefaults instantiates a new PermissionGroupModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionGroupModelWithDefaults() *PermissionGroupModel {
	this := PermissionGroupModel{}
	return &this
}

// GetPermissionGroupId returns the PermissionGroupId field value
func (o *PermissionGroupModel) GetPermissionGroupId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PermissionGroupId
}

// GetPermissionGroupIdOk returns a tuple with the PermissionGroupId field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetPermissionGroupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermissionGroupId, true
}

// SetPermissionGroupId sets field value
func (o *PermissionGroupModel) SetPermissionGroupId(v int64) {
	o.PermissionGroupId = v
}

// GetName returns the Name field value
func (o *PermissionGroupModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PermissionGroupModel) SetName(v string) {
	o.Name = v
}

// GetCanManageMembers returns the CanManageMembers field value
func (o *PermissionGroupModel) GetCanManageMembers() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanManageMembers
}

// GetCanManageMembersOk returns a tuple with the CanManageMembers field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanManageMembersOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanManageMembers, true
}

// SetCanManageMembers sets field value
func (o *PermissionGroupModel) SetCanManageMembers(v bool) {
	o.CanManageMembers = v
}

// GetCanCreateOrUpdateConfig returns the CanCreateOrUpdateConfig field value
func (o *PermissionGroupModel) GetCanCreateOrUpdateConfig() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanCreateOrUpdateConfig
}

// GetCanCreateOrUpdateConfigOk returns a tuple with the CanCreateOrUpdateConfig field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanCreateOrUpdateConfigOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanCreateOrUpdateConfig, true
}

// SetCanCreateOrUpdateConfig sets field value
func (o *PermissionGroupModel) SetCanCreateOrUpdateConfig(v bool) {
	o.CanCreateOrUpdateConfig = v
}

// GetCanDeleteConfig returns the CanDeleteConfig field value
func (o *PermissionGroupModel) GetCanDeleteConfig() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanDeleteConfig
}

// GetCanDeleteConfigOk returns a tuple with the CanDeleteConfig field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanDeleteConfigOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanDeleteConfig, true
}

// SetCanDeleteConfig sets field value
func (o *PermissionGroupModel) SetCanDeleteConfig(v bool) {
	o.CanDeleteConfig = v
}

// GetCanCreateOrUpdateEnvironment returns the CanCreateOrUpdateEnvironment field value
func (o *PermissionGroupModel) GetCanCreateOrUpdateEnvironment() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanCreateOrUpdateEnvironment
}

// GetCanCreateOrUpdateEnvironmentOk returns a tuple with the CanCreateOrUpdateEnvironment field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanCreateOrUpdateEnvironmentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanCreateOrUpdateEnvironment, true
}

// SetCanCreateOrUpdateEnvironment sets field value
func (o *PermissionGroupModel) SetCanCreateOrUpdateEnvironment(v bool) {
	o.CanCreateOrUpdateEnvironment = v
}

// GetCanDeleteEnvironment returns the CanDeleteEnvironment field value
func (o *PermissionGroupModel) GetCanDeleteEnvironment() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanDeleteEnvironment
}

// GetCanDeleteEnvironmentOk returns a tuple with the CanDeleteEnvironment field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanDeleteEnvironmentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanDeleteEnvironment, true
}

// SetCanDeleteEnvironment sets field value
func (o *PermissionGroupModel) SetCanDeleteEnvironment(v bool) {
	o.CanDeleteEnvironment = v
}

// GetCanCreateOrUpdateSetting returns the CanCreateOrUpdateSetting field value
func (o *PermissionGroupModel) GetCanCreateOrUpdateSetting() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanCreateOrUpdateSetting
}

// GetCanCreateOrUpdateSettingOk returns a tuple with the CanCreateOrUpdateSetting field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanCreateOrUpdateSettingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanCreateOrUpdateSetting, true
}

// SetCanCreateOrUpdateSetting sets field value
func (o *PermissionGroupModel) SetCanCreateOrUpdateSetting(v bool) {
	o.CanCreateOrUpdateSetting = v
}

// GetCanTagSetting returns the CanTagSetting field value
func (o *PermissionGroupModel) GetCanTagSetting() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanTagSetting
}

// GetCanTagSettingOk returns a tuple with the CanTagSetting field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanTagSettingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanTagSetting, true
}

// SetCanTagSetting sets field value
func (o *PermissionGroupModel) SetCanTagSetting(v bool) {
	o.CanTagSetting = v
}

// GetCanDeleteSetting returns the CanDeleteSetting field value
func (o *PermissionGroupModel) GetCanDeleteSetting() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanDeleteSetting
}

// GetCanDeleteSettingOk returns a tuple with the CanDeleteSetting field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanDeleteSettingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanDeleteSetting, true
}

// SetCanDeleteSetting sets field value
func (o *PermissionGroupModel) SetCanDeleteSetting(v bool) {
	o.CanDeleteSetting = v
}

// GetCanCreateOrUpdateTag returns the CanCreateOrUpdateTag field value
func (o *PermissionGroupModel) GetCanCreateOrUpdateTag() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanCreateOrUpdateTag
}

// GetCanCreateOrUpdateTagOk returns a tuple with the CanCreateOrUpdateTag field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanCreateOrUpdateTagOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanCreateOrUpdateTag, true
}

// SetCanCreateOrUpdateTag sets field value
func (o *PermissionGroupModel) SetCanCreateOrUpdateTag(v bool) {
	o.CanCreateOrUpdateTag = v
}

// GetCanDeleteTag returns the CanDeleteTag field value
func (o *PermissionGroupModel) GetCanDeleteTag() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanDeleteTag
}

// GetCanDeleteTagOk returns a tuple with the CanDeleteTag field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanDeleteTagOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanDeleteTag, true
}

// SetCanDeleteTag sets field value
func (o *PermissionGroupModel) SetCanDeleteTag(v bool) {
	o.CanDeleteTag = v
}

// GetCanManageWebhook returns the CanManageWebhook field value
func (o *PermissionGroupModel) GetCanManageWebhook() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanManageWebhook
}

// GetCanManageWebhookOk returns a tuple with the CanManageWebhook field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanManageWebhookOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanManageWebhook, true
}

// SetCanManageWebhook sets field value
func (o *PermissionGroupModel) SetCanManageWebhook(v bool) {
	o.CanManageWebhook = v
}

// GetCanUseExportImport returns the CanUseExportImport field value
func (o *PermissionGroupModel) GetCanUseExportImport() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanUseExportImport
}

// GetCanUseExportImportOk returns a tuple with the CanUseExportImport field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanUseExportImportOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanUseExportImport, true
}

// SetCanUseExportImport sets field value
func (o *PermissionGroupModel) SetCanUseExportImport(v bool) {
	o.CanUseExportImport = v
}

// GetCanManageProductPreferences returns the CanManageProductPreferences field value
func (o *PermissionGroupModel) GetCanManageProductPreferences() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanManageProductPreferences
}

// GetCanManageProductPreferencesOk returns a tuple with the CanManageProductPreferences field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanManageProductPreferencesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanManageProductPreferences, true
}

// SetCanManageProductPreferences sets field value
func (o *PermissionGroupModel) SetCanManageProductPreferences(v bool) {
	o.CanManageProductPreferences = v
}

// GetCanManageIntegrations returns the CanManageIntegrations field value
func (o *PermissionGroupModel) GetCanManageIntegrations() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanManageIntegrations
}

// GetCanManageIntegrationsOk returns a tuple with the CanManageIntegrations field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanManageIntegrationsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanManageIntegrations, true
}

// SetCanManageIntegrations sets field value
func (o *PermissionGroupModel) SetCanManageIntegrations(v bool) {
	o.CanManageIntegrations = v
}

// GetCanViewSdkKey returns the CanViewSdkKey field value
func (o *PermissionGroupModel) GetCanViewSdkKey() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanViewSdkKey
}

// GetCanViewSdkKeyOk returns a tuple with the CanViewSdkKey field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanViewSdkKeyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanViewSdkKey, true
}

// SetCanViewSdkKey sets field value
func (o *PermissionGroupModel) SetCanViewSdkKey(v bool) {
	o.CanViewSdkKey = v
}

// GetCanRotateSdkKey returns the CanRotateSdkKey field value
func (o *PermissionGroupModel) GetCanRotateSdkKey() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanRotateSdkKey
}

// GetCanRotateSdkKeyOk returns a tuple with the CanRotateSdkKey field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanRotateSdkKeyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanRotateSdkKey, true
}

// SetCanRotateSdkKey sets field value
func (o *PermissionGroupModel) SetCanRotateSdkKey(v bool) {
	o.CanRotateSdkKey = v
}

// GetCanCreateOrUpdateSegments returns the CanCreateOrUpdateSegments field value
func (o *PermissionGroupModel) GetCanCreateOrUpdateSegments() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanCreateOrUpdateSegments
}

// GetCanCreateOrUpdateSegmentsOk returns a tuple with the CanCreateOrUpdateSegments field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanCreateOrUpdateSegmentsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanCreateOrUpdateSegments, true
}

// SetCanCreateOrUpdateSegments sets field value
func (o *PermissionGroupModel) SetCanCreateOrUpdateSegments(v bool) {
	o.CanCreateOrUpdateSegments = v
}

// GetCanDeleteSegments returns the CanDeleteSegments field value
func (o *PermissionGroupModel) GetCanDeleteSegments() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanDeleteSegments
}

// GetCanDeleteSegmentsOk returns a tuple with the CanDeleteSegments field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanDeleteSegmentsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanDeleteSegments, true
}

// SetCanDeleteSegments sets field value
func (o *PermissionGroupModel) SetCanDeleteSegments(v bool) {
	o.CanDeleteSegments = v
}

// GetCanViewProductAuditLog returns the CanViewProductAuditLog field value
func (o *PermissionGroupModel) GetCanViewProductAuditLog() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanViewProductAuditLog
}

// GetCanViewProductAuditLogOk returns a tuple with the CanViewProductAuditLog field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanViewProductAuditLogOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanViewProductAuditLog, true
}

// SetCanViewProductAuditLog sets field value
func (o *PermissionGroupModel) SetCanViewProductAuditLog(v bool) {
	o.CanViewProductAuditLog = v
}

// GetCanViewProductStatistics returns the CanViewProductStatistics field value
func (o *PermissionGroupModel) GetCanViewProductStatistics() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanViewProductStatistics
}

// GetCanViewProductStatisticsOk returns a tuple with the CanViewProductStatistics field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanViewProductStatisticsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanViewProductStatistics, true
}

// SetCanViewProductStatistics sets field value
func (o *PermissionGroupModel) SetCanViewProductStatistics(v bool) {
	o.CanViewProductStatistics = v
}

// GetCanDisable2FA returns the CanDisable2FA field value
func (o *PermissionGroupModel) GetCanDisable2FA() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanDisable2FA
}

// GetCanDisable2FAOk returns a tuple with the CanDisable2FA field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetCanDisable2FAOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanDisable2FA, true
}

// SetCanDisable2FA sets field value
func (o *PermissionGroupModel) SetCanDisable2FA(v bool) {
	o.CanDisable2FA = v
}

// GetAccessType returns the AccessType field value
func (o *PermissionGroupModel) GetAccessType() AccessType {
	if o == nil {
		var ret AccessType
		return ret
	}

	return o.AccessType
}

// GetAccessTypeOk returns a tuple with the AccessType field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetAccessTypeOk() (*AccessType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessType, true
}

// SetAccessType sets field value
func (o *PermissionGroupModel) SetAccessType(v AccessType) {
	o.AccessType = v
}

// GetNewEnvironmentAccessType returns the NewEnvironmentAccessType field value
func (o *PermissionGroupModel) GetNewEnvironmentAccessType() EnvironmentAccessType {
	if o == nil {
		var ret EnvironmentAccessType
		return ret
	}

	return o.NewEnvironmentAccessType
}

// GetNewEnvironmentAccessTypeOk returns a tuple with the NewEnvironmentAccessType field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetNewEnvironmentAccessTypeOk() (*EnvironmentAccessType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewEnvironmentAccessType, true
}

// SetNewEnvironmentAccessType sets field value
func (o *PermissionGroupModel) SetNewEnvironmentAccessType(v EnvironmentAccessType) {
	o.NewEnvironmentAccessType = v
}

// GetEnvironmentAccesses returns the EnvironmentAccesses field value
func (o *PermissionGroupModel) GetEnvironmentAccesses() []EnvironmentAccessModel {
	if o == nil {
		var ret []EnvironmentAccessModel
		return ret
	}

	return o.EnvironmentAccesses
}

// GetEnvironmentAccessesOk returns a tuple with the EnvironmentAccesses field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetEnvironmentAccessesOk() ([]EnvironmentAccessModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvironmentAccesses, true
}

// SetEnvironmentAccesses sets field value
func (o *PermissionGroupModel) SetEnvironmentAccesses(v []EnvironmentAccessModel) {
	o.EnvironmentAccesses = v
}

// GetProduct returns the Product field value
func (o *PermissionGroupModel) GetProduct() ProductModel {
	if o == nil {
		var ret ProductModel
		return ret
	}

	return o.Product
}

// GetProductOk returns a tuple with the Product field value
// and a boolean to check if the value has been set.
func (o *PermissionGroupModel) GetProductOk() (*ProductModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Product, true
}

// SetProduct sets field value
func (o *PermissionGroupModel) SetProduct(v ProductModel) {
	o.Product = v
}

func (o PermissionGroupModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionGroupModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["permissionGroupId"] = o.PermissionGroupId
	toSerialize["name"] = o.Name
	toSerialize["canManageMembers"] = o.CanManageMembers
	toSerialize["canCreateOrUpdateConfig"] = o.CanCreateOrUpdateConfig
	toSerialize["canDeleteConfig"] = o.CanDeleteConfig
	toSerialize["canCreateOrUpdateEnvironment"] = o.CanCreateOrUpdateEnvironment
	toSerialize["canDeleteEnvironment"] = o.CanDeleteEnvironment
	toSerialize["canCreateOrUpdateSetting"] = o.CanCreateOrUpdateSetting
	toSerialize["canTagSetting"] = o.CanTagSetting
	toSerialize["canDeleteSetting"] = o.CanDeleteSetting
	toSerialize["canCreateOrUpdateTag"] = o.CanCreateOrUpdateTag
	toSerialize["canDeleteTag"] = o.CanDeleteTag
	toSerialize["canManageWebhook"] = o.CanManageWebhook
	toSerialize["canUseExportImport"] = o.CanUseExportImport
	toSerialize["canManageProductPreferences"] = o.CanManageProductPreferences
	toSerialize["canManageIntegrations"] = o.CanManageIntegrations
	toSerialize["canViewSdkKey"] = o.CanViewSdkKey
	toSerialize["canRotateSdkKey"] = o.CanRotateSdkKey
	toSerialize["canCreateOrUpdateSegments"] = o.CanCreateOrUpdateSegments
	toSerialize["canDeleteSegments"] = o.CanDeleteSegments
	toSerialize["canViewProductAuditLog"] = o.CanViewProductAuditLog
	toSerialize["canViewProductStatistics"] = o.CanViewProductStatistics
	toSerialize["canDisable2FA"] = o.CanDisable2FA
	toSerialize["accessType"] = o.AccessType
	toSerialize["newEnvironmentAccessType"] = o.NewEnvironmentAccessType
	toSerialize["environmentAccesses"] = o.EnvironmentAccesses
	toSerialize["product"] = o.Product
	return toSerialize, nil
}

func (o *PermissionGroupModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"permissionGroupId",
		"name",
		"canManageMembers",
		"canCreateOrUpdateConfig",
		"canDeleteConfig",
		"canCreateOrUpdateEnvironment",
		"canDeleteEnvironment",
		"canCreateOrUpdateSetting",
		"canTagSetting",
		"canDeleteSetting",
		"canCreateOrUpdateTag",
		"canDeleteTag",
		"canManageWebhook",
		"canUseExportImport",
		"canManageProductPreferences",
		"canManageIntegrations",
		"canViewSdkKey",
		"canRotateSdkKey",
		"canCreateOrUpdateSegments",
		"canDeleteSegments",
		"canViewProductAuditLog",
		"canViewProductStatistics",
		"canDisable2FA",
		"accessType",
		"newEnvironmentAccessType",
		"environmentAccesses",
		"product",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPermissionGroupModel := _PermissionGroupModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPermissionGroupModel)

	if err != nil {
		return err
	}

	*o = PermissionGroupModel(varPermissionGroupModel)

	return err
}

type NullablePermissionGroupModel struct {
	value *PermissionGroupModel
	isSet bool
}

func (v NullablePermissionGroupModel) Get() *PermissionGroupModel {
	return v.value
}

func (v *NullablePermissionGroupModel) Set(val *PermissionGroupModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionGroupModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionGroupModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionGroupModel(val *PermissionGroupModel) *NullablePermissionGroupModel {
	return &NullablePermissionGroupModel{value: val, isSet: true}
}

func (v NullablePermissionGroupModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionGroupModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


