/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the OrganizationMonthlyStatisticV2Model type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationMonthlyStatisticV2Model{}

// OrganizationMonthlyStatisticV2Model Represents the aggregated monthly usage statistics for an Organization.
type OrganizationMonthlyStatisticV2Model struct {
	// The date for which the aggregate statistics are reported.
	Date time.Time `json:"date"`
	// The total request volume in millions for the period.
	MillionRequestCount float64 `json:"millionRequestCount"`
	// The total network traffic in megabytes for the period.
	ResponseMegaBytes float64 `json:"responseMegaBytes"`
	// Indicates whether the request quota was exceeded.
	OverLimit bool `json:"overLimit"`
	// Indicates whether the network traffic quota was exceeded.
	OverNetworkTrafficLimit bool `json:"overNetworkTrafficLimit"`
	// The monthly request quota limit in millions.
	MillionRequestLimitPerMonth int32 `json:"millionRequestLimitPerMonth"`
	// The monthly network traffic quota limit in gigabytes.
	NetworkTrafficGigaByteLimitPerMonth int32 `json:"networkTrafficGigaByteLimitPerMonth"`
	// The number of Public API calls recorded for the period.
	PublicApiCallCount int64 `json:"publicApiCallCount"`
	AdditionalProperties map[string]interface{}
}

type _OrganizationMonthlyStatisticV2Model OrganizationMonthlyStatisticV2Model

// NewOrganizationMonthlyStatisticV2Model instantiates a new OrganizationMonthlyStatisticV2Model object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationMonthlyStatisticV2Model(date time.Time, millionRequestCount float64, responseMegaBytes float64, overLimit bool, overNetworkTrafficLimit bool, millionRequestLimitPerMonth int32, networkTrafficGigaByteLimitPerMonth int32, publicApiCallCount int64) *OrganizationMonthlyStatisticV2Model {
	this := OrganizationMonthlyStatisticV2Model{}
	this.Date = date
	this.MillionRequestCount = millionRequestCount
	this.ResponseMegaBytes = responseMegaBytes
	this.OverLimit = overLimit
	this.OverNetworkTrafficLimit = overNetworkTrafficLimit
	this.MillionRequestLimitPerMonth = millionRequestLimitPerMonth
	this.NetworkTrafficGigaByteLimitPerMonth = networkTrafficGigaByteLimitPerMonth
	this.PublicApiCallCount = publicApiCallCount
	return &this
}

// NewOrganizationMonthlyStatisticV2ModelWithDefaults instantiates a new OrganizationMonthlyStatisticV2Model object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationMonthlyStatisticV2ModelWithDefaults() *OrganizationMonthlyStatisticV2Model {
	this := OrganizationMonthlyStatisticV2Model{}
	return &this
}

// GetDate returns the Date field value
func (o *OrganizationMonthlyStatisticV2Model) GetDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *OrganizationMonthlyStatisticV2Model) GetDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *OrganizationMonthlyStatisticV2Model) SetDate(v time.Time) {
	o.Date = v
}

// GetMillionRequestCount returns the MillionRequestCount field value
func (o *OrganizationMonthlyStatisticV2Model) GetMillionRequestCount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MillionRequestCount
}

// GetMillionRequestCountOk returns a tuple with the MillionRequestCount field value
// and a boolean to check if the value has been set.
func (o *OrganizationMonthlyStatisticV2Model) GetMillionRequestCountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MillionRequestCount, true
}

// SetMillionRequestCount sets field value
func (o *OrganizationMonthlyStatisticV2Model) SetMillionRequestCount(v float64) {
	o.MillionRequestCount = v
}

// GetResponseMegaBytes returns the ResponseMegaBytes field value
func (o *OrganizationMonthlyStatisticV2Model) GetResponseMegaBytes() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.ResponseMegaBytes
}

// GetResponseMegaBytesOk returns a tuple with the ResponseMegaBytes field value
// and a boolean to check if the value has been set.
func (o *OrganizationMonthlyStatisticV2Model) GetResponseMegaBytesOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseMegaBytes, true
}

// SetResponseMegaBytes sets field value
func (o *OrganizationMonthlyStatisticV2Model) SetResponseMegaBytes(v float64) {
	o.ResponseMegaBytes = v
}

// GetOverLimit returns the OverLimit field value
func (o *OrganizationMonthlyStatisticV2Model) GetOverLimit() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OverLimit
}

// GetOverLimitOk returns a tuple with the OverLimit field value
// and a boolean to check if the value has been set.
func (o *OrganizationMonthlyStatisticV2Model) GetOverLimitOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverLimit, true
}

// SetOverLimit sets field value
func (o *OrganizationMonthlyStatisticV2Model) SetOverLimit(v bool) {
	o.OverLimit = v
}

// GetOverNetworkTrafficLimit returns the OverNetworkTrafficLimit field value
func (o *OrganizationMonthlyStatisticV2Model) GetOverNetworkTrafficLimit() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OverNetworkTrafficLimit
}

// GetOverNetworkTrafficLimitOk returns a tuple with the OverNetworkTrafficLimit field value
// and a boolean to check if the value has been set.
func (o *OrganizationMonthlyStatisticV2Model) GetOverNetworkTrafficLimitOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverNetworkTrafficLimit, true
}

// SetOverNetworkTrafficLimit sets field value
func (o *OrganizationMonthlyStatisticV2Model) SetOverNetworkTrafficLimit(v bool) {
	o.OverNetworkTrafficLimit = v
}

// GetMillionRequestLimitPerMonth returns the MillionRequestLimitPerMonth field value
func (o *OrganizationMonthlyStatisticV2Model) GetMillionRequestLimitPerMonth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MillionRequestLimitPerMonth
}

// GetMillionRequestLimitPerMonthOk returns a tuple with the MillionRequestLimitPerMonth field value
// and a boolean to check if the value has been set.
func (o *OrganizationMonthlyStatisticV2Model) GetMillionRequestLimitPerMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MillionRequestLimitPerMonth, true
}

// SetMillionRequestLimitPerMonth sets field value
func (o *OrganizationMonthlyStatisticV2Model) SetMillionRequestLimitPerMonth(v int32) {
	o.MillionRequestLimitPerMonth = v
}

// GetNetworkTrafficGigaByteLimitPerMonth returns the NetworkTrafficGigaByteLimitPerMonth field value
func (o *OrganizationMonthlyStatisticV2Model) GetNetworkTrafficGigaByteLimitPerMonth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkTrafficGigaByteLimitPerMonth
}

// GetNetworkTrafficGigaByteLimitPerMonthOk returns a tuple with the NetworkTrafficGigaByteLimitPerMonth field value
// and a boolean to check if the value has been set.
func (o *OrganizationMonthlyStatisticV2Model) GetNetworkTrafficGigaByteLimitPerMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkTrafficGigaByteLimitPerMonth, true
}

// SetNetworkTrafficGigaByteLimitPerMonth sets field value
func (o *OrganizationMonthlyStatisticV2Model) SetNetworkTrafficGigaByteLimitPerMonth(v int32) {
	o.NetworkTrafficGigaByteLimitPerMonth = v
}

// GetPublicApiCallCount returns the PublicApiCallCount field value
func (o *OrganizationMonthlyStatisticV2Model) GetPublicApiCallCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PublicApiCallCount
}

// GetPublicApiCallCountOk returns a tuple with the PublicApiCallCount field value
// and a boolean to check if the value has been set.
func (o *OrganizationMonthlyStatisticV2Model) GetPublicApiCallCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicApiCallCount, true
}

// SetPublicApiCallCount sets field value
func (o *OrganizationMonthlyStatisticV2Model) SetPublicApiCallCount(v int64) {
	o.PublicApiCallCount = v
}

func (o OrganizationMonthlyStatisticV2Model) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationMonthlyStatisticV2Model) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["millionRequestCount"] = o.MillionRequestCount
	toSerialize["responseMegaBytes"] = o.ResponseMegaBytes
	toSerialize["overLimit"] = o.OverLimit
	toSerialize["overNetworkTrafficLimit"] = o.OverNetworkTrafficLimit
	toSerialize["millionRequestLimitPerMonth"] = o.MillionRequestLimitPerMonth
	toSerialize["networkTrafficGigaByteLimitPerMonth"] = o.NetworkTrafficGigaByteLimitPerMonth
	toSerialize["publicApiCallCount"] = o.PublicApiCallCount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrganizationMonthlyStatisticV2Model) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"millionRequestCount",
		"responseMegaBytes",
		"overLimit",
		"overNetworkTrafficLimit",
		"millionRequestLimitPerMonth",
		"networkTrafficGigaByteLimitPerMonth",
		"publicApiCallCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationMonthlyStatisticV2Model := _OrganizationMonthlyStatisticV2Model{}

	err = json.Unmarshal(data, &varOrganizationMonthlyStatisticV2Model)

	if err != nil {
		return err
	}

	*o = OrganizationMonthlyStatisticV2Model(varOrganizationMonthlyStatisticV2Model)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "date")
		delete(additionalProperties, "millionRequestCount")
		delete(additionalProperties, "responseMegaBytes")
		delete(additionalProperties, "overLimit")
		delete(additionalProperties, "overNetworkTrafficLimit")
		delete(additionalProperties, "millionRequestLimitPerMonth")
		delete(additionalProperties, "networkTrafficGigaByteLimitPerMonth")
		delete(additionalProperties, "publicApiCallCount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrganizationMonthlyStatisticV2Model struct {
	value *OrganizationMonthlyStatisticV2Model
	isSet bool
}

func (v NullableOrganizationMonthlyStatisticV2Model) Get() *OrganizationMonthlyStatisticV2Model {
	return v.value
}

func (v *NullableOrganizationMonthlyStatisticV2Model) Set(val *OrganizationMonthlyStatisticV2Model) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationMonthlyStatisticV2Model) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationMonthlyStatisticV2Model) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationMonthlyStatisticV2Model(val *OrganizationMonthlyStatisticV2Model) *NullableOrganizationMonthlyStatisticV2Model {
	return &NullableOrganizationMonthlyStatisticV2Model{value: val, isSet: true}
}

func (v NullableOrganizationMonthlyStatisticV2Model) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationMonthlyStatisticV2Model) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


