/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConnectionPreferences type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionPreferences{}

// ConnectionPreferences The connection preferences for the proxy profile, including SDK poll interval and webhook proxy URL.
type ConnectionPreferences struct {
	// The SDK poll interval in seconds that determines how often SDKs should fetch config JSON updates.
	SdkPollInterval int32 `json:"sdkPollInterval"`
	WebhookNotification NullableWebhookNotification `json:"webhookNotification"`
	AdditionalProperties map[string]interface{}
}

type _ConnectionPreferences ConnectionPreferences

// NewConnectionPreferences instantiates a new ConnectionPreferences object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionPreferences(sdkPollInterval int32, webhookNotification NullableWebhookNotification) *ConnectionPreferences {
	this := ConnectionPreferences{}
	this.SdkPollInterval = sdkPollInterval
	this.WebhookNotification = webhookNotification
	return &this
}

// NewConnectionPreferencesWithDefaults instantiates a new ConnectionPreferences object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionPreferencesWithDefaults() *ConnectionPreferences {
	this := ConnectionPreferences{}
	return &this
}

// GetSdkPollInterval returns the SdkPollInterval field value
func (o *ConnectionPreferences) GetSdkPollInterval() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SdkPollInterval
}

// GetSdkPollIntervalOk returns a tuple with the SdkPollInterval field value
// and a boolean to check if the value has been set.
func (o *ConnectionPreferences) GetSdkPollIntervalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SdkPollInterval, true
}

// SetSdkPollInterval sets field value
func (o *ConnectionPreferences) SetSdkPollInterval(v int32) {
	o.SdkPollInterval = v
}

// GetWebhookNotification returns the WebhookNotification field value
// If the value is explicit nil, the zero value for WebhookNotification will be returned
func (o *ConnectionPreferences) GetWebhookNotification() WebhookNotification {
	if o == nil || o.WebhookNotification.Get() == nil {
		var ret WebhookNotification
		return ret
	}

	return *o.WebhookNotification.Get()
}

// GetWebhookNotificationOk returns a tuple with the WebhookNotification field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionPreferences) GetWebhookNotificationOk() (*WebhookNotification, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookNotification.Get(), o.WebhookNotification.IsSet()
}

// SetWebhookNotification sets field value
func (o *ConnectionPreferences) SetWebhookNotification(v WebhookNotification) {
	o.WebhookNotification.Set(&v)
}

func (o ConnectionPreferences) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionPreferences) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sdkPollInterval"] = o.SdkPollInterval
	toSerialize["webhookNotification"] = o.WebhookNotification.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectionPreferences) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sdkPollInterval",
		"webhookNotification",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectionPreferences := _ConnectionPreferences{}

	err = json.Unmarshal(data, &varConnectionPreferences)

	if err != nil {
		return err
	}

	*o = ConnectionPreferences(varConnectionPreferences)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sdkPollInterval")
		delete(additionalProperties, "webhookNotification")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectionPreferences struct {
	value *ConnectionPreferences
	isSet bool
}

func (v NullableConnectionPreferences) Get() *ConnectionPreferences {
	return v.value
}

func (v *NullableConnectionPreferences) Set(val *ConnectionPreferences) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionPreferences) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionPreferences) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionPreferences(val *ConnectionPreferences) *NullableConnectionPreferences {
	return &NullableConnectionPreferences{value: val, isSet: true}
}

func (v NullableConnectionPreferences) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionPreferences) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


