/*
ConfigCat Public Management API

The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 

API version: v1
Contact: support@configcat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configcatpublicapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateOrUpdateProxyProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateProxyProfileRequest{}

// CreateOrUpdateProxyProfileRequest struct for CreateOrUpdateProxyProfileRequest
type CreateOrUpdateProxyProfileRequest struct {
	// The name of the proxy profile.
	Name string `json:"name"`
	// The description of the proxy profile.
	Description NullableString `json:"description,omitempty"`
	ConnectionPreferences NullableCreateOrUpdateConnectionPreferences `json:"connectionPreferences,omitempty"`
	// A collection of selection rules that determine the SDK keys applicable for a proxy profile.
	SdkKeySelectionRules []UpdateProxyProfileSelectionRule `json:"sdkKeySelectionRules,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrUpdateProxyProfileRequest CreateOrUpdateProxyProfileRequest

// NewCreateOrUpdateProxyProfileRequest instantiates a new CreateOrUpdateProxyProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateProxyProfileRequest(name string) *CreateOrUpdateProxyProfileRequest {
	this := CreateOrUpdateProxyProfileRequest{}
	this.Name = name
	return &this
}

// NewCreateOrUpdateProxyProfileRequestWithDefaults instantiates a new CreateOrUpdateProxyProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateProxyProfileRequestWithDefaults() *CreateOrUpdateProxyProfileRequest {
	this := CreateOrUpdateProxyProfileRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateOrUpdateProxyProfileRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateProxyProfileRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateOrUpdateProxyProfileRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateProxyProfileRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateProxyProfileRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateOrUpdateProxyProfileRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateOrUpdateProxyProfileRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateOrUpdateProxyProfileRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateOrUpdateProxyProfileRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetConnectionPreferences returns the ConnectionPreferences field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateProxyProfileRequest) GetConnectionPreferences() CreateOrUpdateConnectionPreferences {
	if o == nil || IsNil(o.ConnectionPreferences.Get()) {
		var ret CreateOrUpdateConnectionPreferences
		return ret
	}
	return *o.ConnectionPreferences.Get()
}

// GetConnectionPreferencesOk returns a tuple with the ConnectionPreferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateProxyProfileRequest) GetConnectionPreferencesOk() (*CreateOrUpdateConnectionPreferences, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConnectionPreferences.Get(), o.ConnectionPreferences.IsSet()
}

// HasConnectionPreferences returns a boolean if a field has been set.
func (o *CreateOrUpdateProxyProfileRequest) HasConnectionPreferences() bool {
	if o != nil && o.ConnectionPreferences.IsSet() {
		return true
	}

	return false
}

// SetConnectionPreferences gets a reference to the given NullableCreateOrUpdateConnectionPreferences and assigns it to the ConnectionPreferences field.
func (o *CreateOrUpdateProxyProfileRequest) SetConnectionPreferences(v CreateOrUpdateConnectionPreferences) {
	o.ConnectionPreferences.Set(&v)
}
// SetConnectionPreferencesNil sets the value for ConnectionPreferences to be an explicit nil
func (o *CreateOrUpdateProxyProfileRequest) SetConnectionPreferencesNil() {
	o.ConnectionPreferences.Set(nil)
}

// UnsetConnectionPreferences ensures that no value is present for ConnectionPreferences, not even an explicit nil
func (o *CreateOrUpdateProxyProfileRequest) UnsetConnectionPreferences() {
	o.ConnectionPreferences.Unset()
}

// GetSdkKeySelectionRules returns the SdkKeySelectionRules field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateProxyProfileRequest) GetSdkKeySelectionRules() []UpdateProxyProfileSelectionRule {
	if o == nil {
		var ret []UpdateProxyProfileSelectionRule
		return ret
	}
	return o.SdkKeySelectionRules
}

// GetSdkKeySelectionRulesOk returns a tuple with the SdkKeySelectionRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateProxyProfileRequest) GetSdkKeySelectionRulesOk() ([]UpdateProxyProfileSelectionRule, bool) {
	if o == nil || IsNil(o.SdkKeySelectionRules) {
		return nil, false
	}
	return o.SdkKeySelectionRules, true
}

// HasSdkKeySelectionRules returns a boolean if a field has been set.
func (o *CreateOrUpdateProxyProfileRequest) HasSdkKeySelectionRules() bool {
	if o != nil && !IsNil(o.SdkKeySelectionRules) {
		return true
	}

	return false
}

// SetSdkKeySelectionRules gets a reference to the given []UpdateProxyProfileSelectionRule and assigns it to the SdkKeySelectionRules field.
func (o *CreateOrUpdateProxyProfileRequest) SetSdkKeySelectionRules(v []UpdateProxyProfileSelectionRule) {
	o.SdkKeySelectionRules = v
}

func (o CreateOrUpdateProxyProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateProxyProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.ConnectionPreferences.IsSet() {
		toSerialize["connectionPreferences"] = o.ConnectionPreferences.Get()
	}
	if o.SdkKeySelectionRules != nil {
		toSerialize["sdkKeySelectionRules"] = o.SdkKeySelectionRules
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrUpdateProxyProfileRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrUpdateProxyProfileRequest := _CreateOrUpdateProxyProfileRequest{}

	err = json.Unmarshal(data, &varCreateOrUpdateProxyProfileRequest)

	if err != nil {
		return err
	}

	*o = CreateOrUpdateProxyProfileRequest(varCreateOrUpdateProxyProfileRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "connectionPreferences")
		delete(additionalProperties, "sdkKeySelectionRules")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrUpdateProxyProfileRequest struct {
	value *CreateOrUpdateProxyProfileRequest
	isSet bool
}

func (v NullableCreateOrUpdateProxyProfileRequest) Get() *CreateOrUpdateProxyProfileRequest {
	return v.value
}

func (v *NullableCreateOrUpdateProxyProfileRequest) Set(val *CreateOrUpdateProxyProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateProxyProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateProxyProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateProxyProfileRequest(val *CreateOrUpdateProxyProfileRequest) *NullableCreateOrUpdateProxyProfileRequest {
	return &NullableCreateOrUpdateProxyProfileRequest{value: val, isSet: true}
}

func (v NullableCreateOrUpdateProxyProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateProxyProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


