name: Public Api Go Client CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.18.x, 1.19.x]
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go mod vendor

    - name: Build
      run: go build -v ./...
